/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import { assertValidRequestParameters } from 'lib/request-parameters.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

/**
 * Client for the Seam API /thermostats/simulate routes.
 */
export class SeamHttpThermostatsSimulate {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  /**
   * Creates a new SeamHttpThermostatsSimulate from an existing HTTP client.
   */
  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpThermostatsSimulate {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpThermostatsSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpThermostatsSimulate authenticated with an API key.
   */
  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpThermostatsSimulate {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpThermostatsSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpThermostatsSimulate authenticated with a client session token.
   */
  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpThermostatsSimulate {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpThermostatsSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpThermostatsSimulate authenticated with a client session token
   * for the user identified by the user identifier key.
   * The client session is created with the publishable key if it does not exist.
   */
  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpThermostatsSimulate> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpThermostatsSimulate.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpThermostatsSimulate.fromClientSessionToken(token, options)
  }

  /**
   * Creates a new SeamHttpThermostatsSimulate authenticated with a console session token
   * and scoped to a workspace.
   */
  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpThermostatsSimulate {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpThermostatsSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpThermostatsSimulate authenticated with a personal access token
   * and scoped to a workspace.
   */
  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpThermostatsSimulate {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpThermostatsSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamPaginator to iterate over the paginated results
   * of the request.
   */
  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  /**
   * Updates the client session token used by this client for authentication.
   *
   * @throws If this client was not created with a client session token.
   */
  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Simulates having adjusted the [HVAC mode](https://docs.seam.co/capability-guides/thermostats/understanding-thermostat-concepts/hvac-mode) for a [thermostat](https://docs.seam.co/capability-guides/thermostats). Only applicable for [sandbox devices](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces). See also [Testing Your Thermostat App with Simulate Endpoints](https://docs.seam.co/capability-guides/thermostats/testing-your-thermostat-app-with-simulate-endpoints).
   */
  hvacModeAdjusted(
    parameters: ThermostatsSimulateHvacModeAdjustedParameters,
    options: ThermostatsSimulateHvacModeAdjustedOptions = {},
  ): ThermostatsSimulateHvacModeAdjustedRequest {
    assertValidRequestParameters(
      parameters,
      '/thermostats/simulate/hvac_mode_adjusted',
      true,
      ['device_id', 'hvac_mode'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/thermostats/simulate/hvac_mode_adjusted',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates a [thermostat](https://docs.seam.co/capability-guides/thermostats) reaching a specified temperature. Only applicable for [sandbox devices](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces). See also [Testing Your Thermostat App with Simulate Endpoints](https://docs.seam.co/capability-guides/thermostats/testing-your-thermostat-app-with-simulate-endpoints).
   */
  temperatureReached(
    parameters: ThermostatsSimulateTemperatureReachedParameters,
    options: ThermostatsSimulateTemperatureReachedOptions = {},
  ): ThermostatsSimulateTemperatureReachedRequest {
    assertValidRequestParameters(
      parameters,
      '/thermostats/simulate/temperature_reached',
      true,
      ['device_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/thermostats/simulate/temperature_reached',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }
}

export type ThermostatsSimulateHvacModeAdjustedParameters = {
  /**
   * ID of the thermostat device for which you want to simulate having adjusted the HVAC mode.
   */
  device_id: string

  /**
   * HVAC mode that you want to simulate.
   */
  hvac_mode: 'off' | 'cool' | 'heat' | 'heat_cool'

  /**
   * Cooling [set point](https://docs.seam.co/capability-guides/thermostats/understanding-thermostat-concepts/set-points) in °C that you want to simulate. You must set `cooling_set_point_celsius` or `cooling_set_point_fahrenheit`.
   */
  cooling_set_point_celsius?: number | undefined
  /**
   * Cooling [set point](https://docs.seam.co/capability-guides/thermostats/understanding-thermostat-concepts/set-points) in °F that you want to simulate. You must set `cooling_set_point_fahrenheit` or `cooling_set_point_celsius`.
   */
  cooling_set_point_fahrenheit?: number | undefined
  /**
   * Heating [set point](https://docs.seam.co/capability-guides/thermostats/understanding-thermostat-concepts/set-points) in °C that you want to simulate. You must set `heating_set_point_celsius` or `heating_set_point_fahrenheit`.
   */
  heating_set_point_celsius?: number | undefined
  /**
   * Heating [set point](https://docs.seam.co/capability-guides/thermostats/understanding-thermostat-concepts/set-points) in °F that you want to simulate. You must set `heating_set_point_fahrenheit` or `heating_set_point_celsius`.
   */
  heating_set_point_fahrenheit?: number | undefined
}

/**
 * @deprecated Use ThermostatsSimulateHvacModeAdjustedRequest instead.
 */
export type ThermostatsSimulateHvacModeAdjustedResponse = void

export type ThermostatsSimulateHvacModeAdjustedRequest = SeamHttpRequest<
  void,
  undefined
>

export interface ThermostatsSimulateHvacModeAdjustedOptions {}

export type ThermostatsSimulateTemperatureReachedParameters = {
  /**
   * ID of the thermostat device that you want to simulate reaching a specified temperature.
   */
  device_id: string

  /**
   * Temperature in °C that you want simulate the thermostat reaching. You must set `temperature_celsius` or `temperature_fahrenheit`.
   */
  temperature_celsius?: number | undefined
  /**
   * Temperature in °F that you want simulate the thermostat reaching. You must set `temperature_fahrenheit` or `temperature_celsius`.
   */
  temperature_fahrenheit?: number | undefined
}

/**
 * @deprecated Use ThermostatsSimulateTemperatureReachedRequest instead.
 */
export type ThermostatsSimulateTemperatureReachedResponse = void

export type ThermostatsSimulateTemperatureReachedRequest = SeamHttpRequest<
  void,
  undefined
>

export interface ThermostatsSimulateTemperatureReachedOptions {}
