/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import { assertValidRequestParameters } from 'lib/request-parameters.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

/**
 * Client for the Seam API /devices/simulate routes.
 */
export class SeamHttpDevicesSimulate {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  /**
   * Creates a new SeamHttpDevicesSimulate from an existing HTTP client.
   */
  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpDevicesSimulate {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpDevicesSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpDevicesSimulate authenticated with an API key.
   */
  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpDevicesSimulate {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpDevicesSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpDevicesSimulate authenticated with a client session token.
   */
  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpDevicesSimulate {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpDevicesSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpDevicesSimulate authenticated with a client session token
   * for the user identified by the user identifier key.
   * The client session is created with the publishable key if it does not exist.
   */
  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpDevicesSimulate> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpDevicesSimulate.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpDevicesSimulate.fromClientSessionToken(token, options)
  }

  /**
   * Creates a new SeamHttpDevicesSimulate authenticated with a console session token
   * and scoped to a workspace.
   */
  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpDevicesSimulate {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpDevicesSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamHttpDevicesSimulate authenticated with a personal access token
   * and scoped to a workspace.
   */
  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpDevicesSimulate {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpDevicesSimulate(constructorOptions)
  }

  /**
   * Creates a new SeamPaginator to iterate over the paginated results
   * of the request.
   */
  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  /**
   * Updates the client session token used by this client for authentication.
   *
   * @throws If this client was not created with a client session token.
   */
  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Simulates connecting a device to Seam. Only applicable for [sandbox devices](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces). See also [Testing Your App Against Device Disconnection and Removal](https://docs.seam.co/core-concepts/devices/testing-your-app-against-device-disconnection-and-removal).
   */
  connect(
    parameters: DevicesSimulateConnectParameters,
    options: DevicesSimulateConnectOptions = {},
  ): DevicesSimulateConnectRequest {
    assertValidRequestParameters(
      parameters,
      '/devices/simulate/connect',
      true,
      ['device_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/devices/simulate/connect',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates bringing the Wi‑Fi hub (bridge) back online for a device.
   * Only applicable for sandbox workspaces and currently
   * implemented for August and TTLock locks.
   * This will clear the `hub_disconnected` error on the device.
   */
  connectToHub(
    parameters: DevicesSimulateConnectToHubParameters,
    options: DevicesSimulateConnectToHubOptions = {},
  ): DevicesSimulateConnectToHubRequest {
    assertValidRequestParameters(
      parameters,
      '/devices/simulate/connect_to_hub',
      true,
      ['device_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/devices/simulate/connect_to_hub',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates disconnecting a device from Seam. Only applicable for [sandbox devices](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces). See also [Testing Your App Against Device Disconnection and Removal](https://docs.seam.co/core-concepts/devices/testing-your-app-against-device-disconnection-and-removal).
   */
  disconnect(
    parameters: DevicesSimulateDisconnectParameters,
    options: DevicesSimulateDisconnectOptions = {},
  ): DevicesSimulateDisconnectRequest {
    assertValidRequestParameters(
      parameters,
      '/devices/simulate/disconnect',
      true,
      ['device_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/devices/simulate/disconnect',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates taking the Wi‑Fi hub (bridge) offline for a device.
   * Only applicable for sandbox workspaces and currently
   * implemented for August, TTLock, and IglooHome devices.
   * This will set the `hub_disconnected` error on the device, or mark the
   * IglooHome bridge offline in sandbox.
   */
  disconnectFromHub(
    parameters: DevicesSimulateDisconnectFromHubParameters,
    options: DevicesSimulateDisconnectFromHubOptions = {},
  ): DevicesSimulateDisconnectFromHubRequest {
    assertValidRequestParameters(
      parameters,
      '/devices/simulate/disconnect_from_hub',
      true,
      ['device_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/devices/simulate/disconnect_from_hub',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Toggle the simulated Nuki Smart Hosting subscription for a device (sandbox only).
   * Send `is_expired: true` to simulate an expired subscription, or `false` to simulate an active subscription.
   * The actual device error is created/cleared by the poller after this state change.
   */
  paidSubscription(
    parameters: DevicesSimulatePaidSubscriptionParameters,
    options: DevicesSimulatePaidSubscriptionOptions = {},
  ): DevicesSimulatePaidSubscriptionRequest {
    assertValidRequestParameters(
      parameters,
      '/devices/simulate/paid_subscription',
      true,
      ['device_id', 'is_expired'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/devices/simulate/paid_subscription',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates removing a device from Seam. Only applicable for [sandbox devices](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces). See also [Testing Your App Against Device Disconnection and Removal](https://docs.seam.co/core-concepts/devices/testing-your-app-against-device-disconnection-and-removal).
   */
  remove(
    parameters: DevicesSimulateRemoveParameters,
    options: DevicesSimulateRemoveOptions = {},
  ): DevicesSimulateRemoveRequest {
    assertValidRequestParameters(parameters, '/devices/simulate/remove', true, [
      'device_id',
    ])

    return new SeamHttpRequest(this, {
      pathname: '/devices/simulate/remove',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }
}

export type DevicesSimulateConnectParameters = {
  /**
   * ID of the device that you want to simulate connecting to Seam.
   */
  device_id: string
}

/**
 * @deprecated Use DevicesSimulateConnectRequest instead.
 */
export type DevicesSimulateConnectResponse = void

export type DevicesSimulateConnectRequest = SeamHttpRequest<void, undefined>

export interface DevicesSimulateConnectOptions {}

export type DevicesSimulateConnectToHubParameters = {
  /**
   * ID of the device whose hub you want to reconnect.
   */
  device_id: string
}

/**
 * @deprecated Use DevicesSimulateConnectToHubRequest instead.
 */
export type DevicesSimulateConnectToHubResponse = void

export type DevicesSimulateConnectToHubRequest = SeamHttpRequest<
  void,
  undefined
>

export interface DevicesSimulateConnectToHubOptions {}

export type DevicesSimulateDisconnectParameters = {
  /**
   * ID of the device that you want to simulate disconnecting from Seam.
   */
  device_id: string
}

/**
 * @deprecated Use DevicesSimulateDisconnectRequest instead.
 */
export type DevicesSimulateDisconnectResponse = void

export type DevicesSimulateDisconnectRequest = SeamHttpRequest<void, undefined>

export interface DevicesSimulateDisconnectOptions {}

export type DevicesSimulateDisconnectFromHubParameters = {
  /**
   * ID of the device whose hub you want to disconnect.
   */
  device_id: string
}

/**
 * @deprecated Use DevicesSimulateDisconnectFromHubRequest instead.
 */
export type DevicesSimulateDisconnectFromHubResponse = void

export type DevicesSimulateDisconnectFromHubRequest = SeamHttpRequest<
  void,
  undefined
>

export interface DevicesSimulateDisconnectFromHubOptions {}

export type DevicesSimulatePaidSubscriptionParameters = {
  device_id: string

  is_expired: boolean
}

/**
 * @deprecated Use DevicesSimulatePaidSubscriptionRequest instead.
 */
export type DevicesSimulatePaidSubscriptionResponse = void

export type DevicesSimulatePaidSubscriptionRequest = SeamHttpRequest<
  void,
  undefined
>

export interface DevicesSimulatePaidSubscriptionOptions {}

export type DevicesSimulateRemoveParameters = {
  /**
   * ID of the device that you want to simulate removing from Seam.
   */
  device_id: string
}

/**
 * @deprecated Use DevicesSimulateRemoveRequest instead.
 */
export type DevicesSimulateRemoveResponse = void

export type DevicesSimulateRemoveRequest = SeamHttpRequest<void, undefined>

export interface DevicesSimulateRemoveOptions {}
