/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import type { ActionAttempt } from 'lib/resources/action-attempt.js'
import type { Workspace } from 'lib/resources/workspace.js'
import { SeamHttpActionAttempts } from 'lib/routes/action-attempts/index.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

/**
 * Client for the Seam API /workspaces routes.
 */
export class SeamHttpWorkspaces {
  /**
   * The client used to make HTTP requests to the Seam API.
   */
  client: Client

  /**
   * Default request options used for requests made by this client.
   */
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  /**
   * Creates a new SeamHttpWorkspaces from an existing HTTP client.
   */
  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpWorkspaces {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpWorkspaces(constructorOptions)
  }

  /**
   * Creates a new SeamHttpWorkspaces authenticated with an API key.
   */
  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpWorkspaces {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpWorkspaces(constructorOptions)
  }

  /**
   * Creates a new SeamHttpWorkspaces authenticated with a client session token.
   */
  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpWorkspaces {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpWorkspaces(constructorOptions)
  }

  /**
   * Creates a new SeamHttpWorkspaces authenticated with a client session token
   * for the user identified by the user identifier key.
   * The client session is created with the publishable key if it does not exist.
   */
  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpWorkspaces> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpWorkspaces.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpWorkspaces.fromClientSessionToken(token, options)
  }

  /**
   * Creates a new SeamHttpWorkspaces authenticated with a console session token
   * and scoped to a workspace.
   */
  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpWorkspaces {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpWorkspaces(constructorOptions)
  }

  /**
   * Creates a new SeamHttpWorkspaces authenticated with a personal access token
   * and scoped to a workspace.
   */
  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpWorkspaces {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpWorkspaces(constructorOptions)
  }

  /**
   * Creates a new SeamPaginator to iterate over the paginated results
   * of the request.
   */
  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  /**
   * Updates the client session token used by this client for authentication.
   *
   * @throws If this client was not created with a client session token.
   */
  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Creates a new [workspace](https://docs.seam.co/core-concepts/workspaces).
   */
  create(
    parameters: WorkspacesCreateParameters,
    options: WorkspacesCreateOptions = {},
  ): WorkspacesCreateRequest {
    return new SeamHttpRequest(this, {
      pathname: '/workspaces/create',
      method: 'POST',
      body: parameters,
      responseKey: 'workspace',
      options,
    })
  }

  /**
   * Returns the [workspace](https://docs.seam.co/core-concepts/workspaces) associated with the authentication value.
   */
  get(
    parameters?: WorkspacesGetParameters,
    options: WorkspacesGetOptions = {},
  ): WorkspacesGetRequest {
    return new SeamHttpRequest(this, {
      pathname: '/workspaces/get',
      method: 'GET',
      params: parameters,
      responseKey: 'workspace',
      options,
    })
  }

  /**
   * Returns a list of [workspaces](https://docs.seam.co/core-concepts/workspaces) associated with the authentication value.
   */
  list(
    parameters?: WorkspacesListParameters,
    options: WorkspacesListOptions = {},
  ): WorkspacesListRequest {
    return new SeamHttpRequest(this, {
      pathname: '/workspaces/list',
      method: 'GET',
      params: parameters,
      responseKey: 'workspaces',
      options,
    })
  }

  /**
   * Resets the [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces) associated with the authentication value. Note that this endpoint is only available for sandbox workspaces.
   */
  resetSandbox(
    parameters?: WorkspacesResetSandboxParameters,
    options: WorkspacesResetSandboxOptions = {},
  ): WorkspacesResetSandboxRequest {
    return new SeamHttpRequest(this, {
      pathname: '/workspaces/reset_sandbox',
      method: 'POST',
      body: parameters,
      responseKey: 'action_attempt',
      options,
      actionAttempts: SeamHttpActionAttempts.fromClient(this.client, {
        ...this.defaults,
        waitForActionAttempt: false,
      }),
    })
  }

  /**
   * Updates the [workspace](https://docs.seam.co/core-concepts/workspaces) associated with the authentication value.
   */
  update(
    parameters?: WorkspacesUpdateParameters,
    options: WorkspacesUpdateOptions = {},
  ): WorkspacesUpdateRequest {
    return new SeamHttpRequest(this, {
      pathname: '/workspaces/update',
      method: 'PATCH',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }
}

/**
 * Parameters for `SeamHttpWorkspaces.create`.
 */
export type WorkspacesCreateParameters = {
  /**
   * Company name for the new workspace.
   */
  company_name?: string | undefined
  /**
   * Connect partner name for the new workspace.
   *
   * @deprecated Use `company_name` instead.
   */
  connect_partner_name?: string | undefined
  /**
   * [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews) customizations for the new workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
   */
  connect_webview_customization?:
    | {
        /**
         * Logo shape for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the new workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        logo_shape?: 'circle' | 'square' | undefined
        /**
         * Primary button color for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the new workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        primary_button_color?: string | undefined
        /**
         * Primary button text color for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the new workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        primary_button_text_color?: string | undefined
        /**
         * Success message for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the new workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        success_message?: string | undefined
      }
    | undefined
  /**
   * Indicates whether the new workspace is a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  is_sandbox?: boolean | undefined
  /**
   * Name of the new workspace.
   */
  name: string

  /**
   * ID of the organization to associate with the new workspace.
   */
  organization_id?: string | undefined
  /**
   * @deprecated Use `connect_webview_customization.webview_logo_shape` instead.
   */
  webview_logo_shape?: 'circle' | 'square' | undefined
  /**
   * @deprecated Use `connect_webview_customization.webview_primary_button_color` instead.
   */
  webview_primary_button_color?: string | undefined
  /**
   * @deprecated Use `connect_webview_customization.webview_primary_button_text_color` instead.
   */
  webview_primary_button_text_color?: string | undefined
  /**
   * @deprecated Use `connect_webview_customization.webview_success_message` instead.
   */
  webview_success_message?: string | undefined
}

/**
 * Response from `SeamHttpWorkspaces.create`.
 *
 * @deprecated Use WorkspacesCreateRequest instead.
 */
export type WorkspacesCreateResponse = { workspace: Workspace }

/**
 * Request returned by `SeamHttpWorkspaces.create`.
 */
export type WorkspacesCreateRequest = SeamHttpRequest<
  WorkspacesCreateResponse,
  'workspace'
>

/**
 * Options for `SeamHttpWorkspaces.create`.
 */
export interface WorkspacesCreateOptions {}

/**
 * Parameters for `SeamHttpWorkspaces.get`.
 */
export type WorkspacesGetParameters = {}

/**
 * Response from `SeamHttpWorkspaces.get`.
 *
 * @deprecated Use WorkspacesGetRequest instead.
 */
export type WorkspacesGetResponse = { workspace: Workspace }

/**
 * Request returned by `SeamHttpWorkspaces.get`.
 */
export type WorkspacesGetRequest = SeamHttpRequest<
  WorkspacesGetResponse,
  'workspace'
>

/**
 * Options for `SeamHttpWorkspaces.get`.
 */
export interface WorkspacesGetOptions {}

/**
 * Parameters for `SeamHttpWorkspaces.list`.
 */
export type WorkspacesListParameters = {}

/**
 * Response from `SeamHttpWorkspaces.list`.
 *
 * @deprecated Use WorkspacesListRequest instead.
 */
export type WorkspacesListResponse = { workspaces: Array<Workspace> }

/**
 * Request returned by `SeamHttpWorkspaces.list`.
 */
export type WorkspacesListRequest = SeamHttpRequest<
  WorkspacesListResponse,
  'workspaces'
>

/**
 * Options for `SeamHttpWorkspaces.list`.
 */
export interface WorkspacesListOptions {}

/**
 * Parameters for `SeamHttpWorkspaces.resetSandbox`.
 */
export type WorkspacesResetSandboxParameters = {}

/**
 * Response from `SeamHttpWorkspaces.resetSandbox`.
 *
 * @deprecated Use WorkspacesResetSandboxRequest instead.
 */
export type WorkspacesResetSandboxResponse = { action_attempt: ActionAttempt }

/**
 * Request returned by `SeamHttpWorkspaces.resetSandbox`.
 */
export type WorkspacesResetSandboxRequest = SeamHttpRequest<
  WorkspacesResetSandboxResponse,
  'action_attempt'
>

/**
 * Options for `SeamHttpWorkspaces.resetSandbox`.
 */
export type WorkspacesResetSandboxOptions = Pick<
  SeamHttpRequestOptions,
  'waitForActionAttempt'
>

/**
 * Parameters for `SeamHttpWorkspaces.update`.
 */
export type WorkspacesUpdateParameters = {
  /**
   * Connect partner name for the workspace.
   */
  connect_partner_name?: string | undefined
  /**
   * [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews) customizations for the workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
   */
  connect_webview_customization?:
    | {
        /**
         * Logo shape for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        logo_shape?: 'circle' | 'square' | undefined
        /**
         * Primary button color for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        primary_button_color?: string | undefined
        /**
         * Primary button text color for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        primary_button_text_color?: string | undefined
        /**
         * Success message for [Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews) in the workspace. See also [Customize the Look and Feel of Your Connect Webviews](https://docs.seam.co/core-concepts/connect-webviews/customizing-connect-webviews#customize-the-look-and-feel-of-your-connect-webviews).
         */
        success_message?: string | undefined
      }
    | undefined
  /**
   * Indicates whether publishable key authentication is enabled for this workspace.
   */
  is_publishable_key_auth_enabled?: boolean | undefined
  /**
   * Indicates whether the workspace is suspended.
   */
  is_suspended?: boolean | undefined
  /**
   * Name of the workspace.
   */
  name?: string | undefined
  /**
   * ID of the organization to assign the workspace to. The authenticated user must be the owner of the workspace and an admin of the target organization.
   */
  organization_id?: string | undefined
}

/**
 * Response from `SeamHttpWorkspaces.update`.
 *
 * @deprecated Use WorkspacesUpdateRequest instead.
 */
export type WorkspacesUpdateResponse = void

/**
 * Request returned by `SeamHttpWorkspaces.update`.
 */
export type WorkspacesUpdateRequest = SeamHttpRequest<void, undefined>

/**
 * Options for `SeamHttpWorkspaces.update`.
 */
export interface WorkspacesUpdateOptions {}
