/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import { seamApiLtsVersion } from 'lib/lts-version.js'
import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/seam/connect/auth.js'
import { type Client, createClient } from 'lib/seam/connect/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/seam/connect/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/seam/connect/parse-options.js'
import type { AcsEntranceResource } from 'lib/seam/connect/resources/acs-entrance.js'
import type { AcsUserResource } from 'lib/seam/connect/resources/acs-user.js'
import { SeamHttpClientSessions } from 'lib/seam/connect/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam/connect/seam-http-request.js'
import { SeamPaginator } from 'lib/seam/connect/seam-paginator.js'

export class SeamHttpAcsUsers {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>
  readonly ltsVersion = seamApiLtsVersion
  static ltsVersion = seamApiLtsVersion

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpAcsUsers {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpAcsUsers(constructorOptions)
  }

  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpAcsUsers {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpAcsUsers(constructorOptions)
  }

  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpAcsUsers {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpAcsUsers(constructorOptions)
  }

  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpAcsUsers> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpAcsUsers.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpAcsUsers.fromClientSessionToken(token, options)
  }

  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpAcsUsers {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpAcsUsers(constructorOptions)
  }

  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpAcsUsers {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpAcsUsers(constructorOptions)
  }

  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  addToAccessGroup(
    parameters: AcsUsersAddToAccessGroupParameters,
    options: AcsUsersAddToAccessGroupOptions = {},
  ): AcsUsersAddToAccessGroupRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/add_to_access_group',
      method: 'PUT',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  create(
    parameters: AcsUsersCreateParameters,
    options: AcsUsersCreateOptions = {},
  ): AcsUsersCreateRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/create',
      method: 'POST',
      body: parameters,
      responseKey: 'acs_user',
      options,
    })
  }

  delete(
    parameters?: AcsUsersDeleteParameters,
    options: AcsUsersDeleteOptions = {},
  ): AcsUsersDeleteRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/delete',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  get(
    parameters?: AcsUsersGetParameters,
    options: AcsUsersGetOptions = {},
  ): AcsUsersGetRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/get',
      method: 'POST',
      body: parameters,
      responseKey: 'acs_user',
      options,
    })
  }

  list(
    parameters?: AcsUsersListParameters,
    options: AcsUsersListOptions = {},
  ): AcsUsersListRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/list',
      method: 'POST',
      body: parameters,
      responseKey: 'acs_users',
      options,
    })
  }

  listAccessibleEntrances(
    parameters?: AcsUsersListAccessibleEntrancesParameters,
    options: AcsUsersListAccessibleEntrancesOptions = {},
  ): AcsUsersListAccessibleEntrancesRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/list_accessible_entrances',
      method: 'POST',
      body: parameters,
      responseKey: 'acs_entrances',
      options,
    })
  }

  removeFromAccessGroup(
    parameters: AcsUsersRemoveFromAccessGroupParameters,
    options: AcsUsersRemoveFromAccessGroupOptions = {},
  ): AcsUsersRemoveFromAccessGroupRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/remove_from_access_group',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  revokeAccessToAllEntrances(
    parameters?: AcsUsersRevokeAccessToAllEntrancesParameters,
    options: AcsUsersRevokeAccessToAllEntrancesOptions = {},
  ): AcsUsersRevokeAccessToAllEntrancesRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/revoke_access_to_all_entrances',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  suspend(
    parameters?: AcsUsersSuspendParameters,
    options: AcsUsersSuspendOptions = {},
  ): AcsUsersSuspendRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/suspend',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  unsuspend(
    parameters?: AcsUsersUnsuspendParameters,
    options: AcsUsersUnsuspendOptions = {},
  ): AcsUsersUnsuspendRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/unsuspend',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  update(
    parameters?: AcsUsersUpdateParameters,
    options: AcsUsersUpdateOptions = {},
  ): AcsUsersUpdateRequest {
    return new SeamHttpRequest(this, {
      pathname: '/acs/users/update',
      method: 'PATCH',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }
}

export type AcsUsersAddToAccessGroupParameters = {
  acs_access_group_id: string

  acs_user_id: string
}

/**
 * @deprecated Use AcsUsersAddToAccessGroupRequest instead.
 */
export type AcsUsersAddToAccessGroupResponse = void

export type AcsUsersAddToAccessGroupRequest = SeamHttpRequest<void, undefined>

export interface AcsUsersAddToAccessGroupOptions {}

export type AcsUsersCreateParameters = {
  access_schedule?:
    | {
        ends_at?: string | undefined
        starts_at?: string | undefined
      }
    | undefined
  acs_access_group_ids?: Array<string> | undefined
  acs_system_id: string

  email?: string | undefined
  email_address?: string | undefined
  full_name: string

  phone_number?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersCreateRequest instead.
 */
export type AcsUsersCreateResponse = { acs_user: AcsUserResource }

export type AcsUsersCreateRequest = SeamHttpRequest<
  AcsUsersCreateResponse,
  'acs_user'
>

export interface AcsUsersCreateOptions {}

export type AcsUsersDeleteParameters = {
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersDeleteRequest instead.
 */
export type AcsUsersDeleteResponse = void

export type AcsUsersDeleteRequest = SeamHttpRequest<void, undefined>

export interface AcsUsersDeleteOptions {}

export type AcsUsersGetParameters = {
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersGetRequest instead.
 */
export type AcsUsersGetResponse = { acs_user: AcsUserResource }

export type AcsUsersGetRequest = SeamHttpRequest<
  AcsUsersGetResponse,
  'acs_user'
>

export interface AcsUsersGetOptions {}

export type AcsUsersListParameters = {
  acs_system_id?: string | undefined
  created_before?: string | undefined
  limit?: number | undefined
  page_cursor?: string | undefined
  search?: string | undefined
  user_identity_email_address?: string | undefined
  user_identity_id?: string | undefined
  user_identity_phone_number?: string | undefined
}

/**
 * @deprecated Use AcsUsersListRequest instead.
 */
export type AcsUsersListResponse = { acs_users: Array<AcsUserResource> }

export type AcsUsersListRequest = SeamHttpRequest<
  AcsUsersListResponse,
  'acs_users'
>

export interface AcsUsersListOptions {}

export type AcsUsersListAccessibleEntrancesParameters = {
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersListAccessibleEntrancesRequest instead.
 */
export type AcsUsersListAccessibleEntrancesResponse = {
  acs_entrances: Array<AcsEntranceResource>
}

export type AcsUsersListAccessibleEntrancesRequest = SeamHttpRequest<
  AcsUsersListAccessibleEntrancesResponse,
  'acs_entrances'
>

export interface AcsUsersListAccessibleEntrancesOptions {}

export type AcsUsersRemoveFromAccessGroupParameters = {
  acs_access_group_id: string

  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersRemoveFromAccessGroupRequest instead.
 */
export type AcsUsersRemoveFromAccessGroupResponse = void

export type AcsUsersRemoveFromAccessGroupRequest = SeamHttpRequest<
  void,
  undefined
>

export interface AcsUsersRemoveFromAccessGroupOptions {}

export type AcsUsersRevokeAccessToAllEntrancesParameters = {
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersRevokeAccessToAllEntrancesRequest instead.
 */
export type AcsUsersRevokeAccessToAllEntrancesResponse = void

export type AcsUsersRevokeAccessToAllEntrancesRequest = SeamHttpRequest<
  void,
  undefined
>

export interface AcsUsersRevokeAccessToAllEntrancesOptions {}

export type AcsUsersSuspendParameters = {
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersSuspendRequest instead.
 */
export type AcsUsersSuspendResponse = void

export type AcsUsersSuspendRequest = SeamHttpRequest<void, undefined>

export interface AcsUsersSuspendOptions {}

export type AcsUsersUnsuspendParameters = {
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersUnsuspendRequest instead.
 */
export type AcsUsersUnsuspendResponse = void

export type AcsUsersUnsuspendRequest = SeamHttpRequest<void, undefined>

export interface AcsUsersUnsuspendOptions {}

export type AcsUsersUpdateParameters = {
  access_schedule?:
    | {
        ends_at?: string | undefined
        starts_at?: string | undefined
      }
    | undefined
  acs_system_id?: string | undefined
  acs_user_id?: string | undefined
  email?: string | undefined
  email_address?: string | undefined
  full_name?: string | undefined
  hid_acs_system_id?: string | undefined
  phone_number?: string | undefined
  user_identity_id?: string | undefined
}

/**
 * @deprecated Use AcsUsersUpdateRequest instead.
 */
export type AcsUsersUpdateResponse = void

export type AcsUsersUpdateRequest = SeamHttpRequest<void, undefined>

export interface AcsUsersUpdateOptions {}
