/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import type { RouteRequestBody, RouteResponse } from '@seamapi/types/connect'

import { seamApiLtsVersion } from 'lib/lts-version.js'
import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/seam/connect/auth.js'
import { type Client, createClient } from 'lib/seam/connect/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/seam/connect/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/seam/connect/parse-options.js'
import { SeamHttpClientSessions } from 'lib/seam/connect/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam/connect/seam-http-request.js'
import { SeamPaginator } from 'lib/seam/connect/seam-paginator.js'
import type { SetNonNullable } from 'lib/types.js'

export class SeamHttpSeamCustomerV1ConnectorsIcal {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>
  readonly ltsVersion = seamApiLtsVersion
  static ltsVersion = seamApiLtsVersion

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    if (!options.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpSeamCustomerV1ConnectorsIcal {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpSeamCustomerV1ConnectorsIcal(constructorOptions)
  }

  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpSeamCustomerV1ConnectorsIcal {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpSeamCustomerV1ConnectorsIcal(constructorOptions)
  }

  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpSeamCustomerV1ConnectorsIcal {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpSeamCustomerV1ConnectorsIcal(constructorOptions)
  }

  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpSeamCustomerV1ConnectorsIcal> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpSeamCustomerV1ConnectorsIcal.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpSeamCustomerV1ConnectorsIcal.fromClientSessionToken(
      token,
      options,
    )
  }

  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpSeamCustomerV1ConnectorsIcal {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpSeamCustomerV1ConnectorsIcal(constructorOptions)
  }

  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpSeamCustomerV1ConnectorsIcal {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpSeamCustomerV1ConnectorsIcal(constructorOptions)
  }

  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  generateConfig(
    parameters?: SeamCustomerV1ConnectorsIcalGenerateConfigParameters,
    options: SeamCustomerV1ConnectorsIcalGenerateConfigOptions = {},
  ): SeamCustomerV1ConnectorsIcalGenerateConfigRequest {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname: '/seam/customer/v1/connectors/ical/generate-config',
      method: 'POST',
      body: parameters,
      responseKey: 'generated_config',
      options,
    })
  }

  validateConfig(
    parameters?: SeamCustomerV1ConnectorsIcalValidateConfigParameters,
    options: SeamCustomerV1ConnectorsIcalValidateConfigOptions = {},
  ): SeamCustomerV1ConnectorsIcalValidateConfigRequest {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname: '/seam/customer/v1/connectors/ical/validate-config',
      method: 'POST',
      body: parameters,
      responseKey: 'validation_result',
      options,
    })
  }
}

export type SeamCustomerV1ConnectorsIcalGenerateConfigParameters =
  RouteRequestBody<'/seam/customer/v1/connectors/ical/generate-config'>

/**
 * @deprecated Use SeamCustomerV1ConnectorsIcalGenerateConfigParameters instead.
 */
export type SeamCustomerV1ConnectorsIcalGenerateConfigBody =
  SeamCustomerV1ConnectorsIcalGenerateConfigParameters

/**
 * @deprecated Use SeamCustomerV1ConnectorsIcalGenerateConfigRequest instead.
 */
export type SeamCustomerV1ConnectorsIcalGenerateConfigResponse = SetNonNullable<
  Required<RouteResponse<'/seam/customer/v1/connectors/ical/generate-config'>>
>

export type SeamCustomerV1ConnectorsIcalGenerateConfigRequest = SeamHttpRequest<
  SeamCustomerV1ConnectorsIcalGenerateConfigResponse,
  'generated_config'
>

export interface SeamCustomerV1ConnectorsIcalGenerateConfigOptions {}

export type SeamCustomerV1ConnectorsIcalValidateConfigParameters =
  RouteRequestBody<'/seam/customer/v1/connectors/ical/validate-config'>

/**
 * @deprecated Use SeamCustomerV1ConnectorsIcalValidateConfigParameters instead.
 */
export type SeamCustomerV1ConnectorsIcalValidateConfigBody =
  SeamCustomerV1ConnectorsIcalValidateConfigParameters

/**
 * @deprecated Use SeamCustomerV1ConnectorsIcalValidateConfigRequest instead.
 */
export type SeamCustomerV1ConnectorsIcalValidateConfigResponse = SetNonNullable<
  Required<RouteResponse<'/seam/customer/v1/connectors/ical/validate-config'>>
>

export type SeamCustomerV1ConnectorsIcalValidateConfigRequest = SeamHttpRequest<
  SeamCustomerV1ConnectorsIcalValidateConfigResponse,
  'validation_result'
>

export interface SeamCustomerV1ConnectorsIcalValidateConfigOptions {}
