/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

/**
 * Represents an [access control system](https://docs.seam.co/low-level-apis/access-systems).
 *
 * Within an `acs_system`, create [`acs_user`s](https://docs.seam.co/api/acs/users/object) and [`acs_credential`s](https://docs.seam.co/api/acs/credentials/object) to grant access to the `acs_user`s.
 *
 * For details about the resources associated with an access control system, see the [access control systems namespace](https://docs.seam.co/api/acs).
 */
export type AcsSystem = {
  /**
   * Number of access groups in the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  acs_access_group_count?: number | undefined
  /**
   * ID of the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  acs_system_id: string

  /**
   * Number of users in the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  acs_user_count?: number | undefined
  /**
   * ID of the connected account associated with the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  connected_account_id: string

  /**
   * IDs of the [connected accounts](https://docs.seam.co/core-concepts/connected-accounts) associated with the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   * @deprecated Use `connected_account_id`.
   */
  connected_account_ids: Array<string>

  /**
   * Date and time at which the [access control system](https://docs.seam.co/low-level-apis/access-systems) was created.
   */
  created_at: string

  /**
   * ID of the default credential manager `acs_system` for this [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  default_credential_manager_acs_system_id?: string | null | undefined
  /**
   * Errors associated with the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  errors: Array<
    /**
     * Indicates that the Seam API cannot communicate with [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge), for example, if Seam Bridge executable has stopped or if the computer running the Seam Bridge executable is offline.
     * This error might also occur if Seam Bridge is connected to the wrong [workspace](https://docs.seam.co/core-concepts/workspaces).
     * See also [Troubleshooting Your Access Control System](https://docs.seam.co/low-level-apis/access-systems/troubleshooting-your-access-control-system#acs_system-errors-seam_bridge_disconnected).
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'seam_bridge_disconnected'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the Seam API cannot communicate with [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge), for example, if Seam Bridge executable has stopped or if the computer running the Seam Bridge executable is offline.
     * See also [Troubleshooting Your Access Control System](https://docs.seam.co/low-level-apis/access-systems/troubleshooting-your-access-control-system#acs_system-errors-seam_bridge_disconnected).
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'bridge_disconnected'

        /**
         * Indicates whether the error is related to the [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge).
         */
        is_bridge_error?: boolean | undefined
        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge) is functioning correctly and the Seam API can communicate with Seam Bridge, but the Seam API cannot connect to the on-premises [Visionline access control system](https://docs.seam.co/device-and-system-integration-guides/assa-abloy-visionline-access-control-system).
     * For example, the IP address of the on-premises access control system may be set incorrectly within the Seam [workspace](https://docs.seam.co/core-concepts/workspaces).
     * See also [Troubleshooting Your Access Control System](https://docs.seam.co/low-level-apis/access-systems/troubleshooting-your-access-control-system#acs_system-errors-visionline_instance_unreachable).
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'visionline_instance_unreachable'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the maximum number of users allowed for the site has been reached. This means that new access codes cannot be created. Contact Salto support to increase the user limit.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'salto_ks_subscription_limit_exceeded'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access control system](https://docs.seam.co/low-level-apis/access-systems) has been disconnected. See [Troubleshooting Your Access Control System](https://docs.seam.co/low-level-apis/access-systems/troubleshooting-your-access-control-system) to resolve the issue.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'acs_system_disconnected'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the login credentials are invalid. Reconnect the account using a [Connect Webview](https://docs.seam.co/core-concepts/connect-webviews) to restore access.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'account_disconnected'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access control system](https://docs.seam.co/low-level-apis/access-systems) has lost its Salto KS certification. Contact [support](mailto:support@seam.co) to regain access.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'salto_ks_certification_expired'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the access control system provider's service is temporarily unavailable. Seam will automatically retry and reconnect when the service becomes available again.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        /**
         * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
         */
        error_code: 'provider_service_unavailable'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      }
  >

  /**
   * Brand-specific terminology for the [access control system](https://docs.seam.co/low-level-apis/access-systems) type.
   */
  external_type?:
    | 'pti_site'
    | 'avigilon_alta_org'
    | 'salto_ks_site'
    | 'salto_space_system'
    | 'brivo_account'
    | 'hid_credential_manager_organization'
    | 'visionline_system'
    | 'assa_abloy_credential_service'
    | 'latch_building'
    | 'dormakaba_community_site'
    | 'dormakaba_ambiance_site'
    | 'legic_connect_credential_service'
    | 'assa_abloy_vostio'
    | 'assa_abloy_vostio_credential_service'
    | 'hotek_site'
    | 'kisi_organization'
    | 'akiles_organization'
    | undefined
  /**
   * Display name that corresponds to the brand-specific terminology for the [access control system](https://docs.seam.co/low-level-apis/access-systems) type.
   */
  external_type_display_name?: string | undefined
  /**
   * Alternative text for the [access control system](https://docs.seam.co/low-level-apis/access-systems) image.
   */
  image_alt_text: string

  /**
   * URL for the image that represents the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  image_url: string

  /**
   * Indicates whether the `acs_system` is a credential manager.
   */
  is_credential_manager: boolean

  /**
   * Location information for the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  location: {
    /**
     * Time zone in which the [access control system](https://docs.seam.co/low-level-apis/access-systems) is located.
     */
    time_zone: string | null
  }

  /**
   * Name of the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  name: string

  /**
   * @deprecated Use `external_type`.
   */
  system_type?:
    | 'pti_site'
    | 'avigilon_alta_org'
    | 'salto_ks_site'
    | 'salto_space_system'
    | 'brivo_account'
    | 'hid_credential_manager_organization'
    | 'visionline_system'
    | 'assa_abloy_credential_service'
    | 'latch_building'
    | 'dormakaba_community_site'
    | 'dormakaba_ambiance_site'
    | 'legic_connect_credential_service'
    | 'assa_abloy_vostio'
    | 'assa_abloy_vostio_credential_service'
    | 'hotek_site'
    | 'kisi_organization'
    | 'akiles_organization'
    | undefined
  /**
   * @deprecated Use `external_type_display_name`.
   */
  system_type_display_name?: string | undefined
  /**
   * Visionline-specific metadata for the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  visionline_metadata?:
    | {
        /**
         * IP address or hostname of the main Visionline server relative to [Seam Bridge](https://docs.seam.co/capability-guides/seam-bridge) on the local network.
         */
        lan_address?: string | undefined
        /**
         * Keyset loaded into a reader. Mobile keys and reader administration tools securely authenticate only with readers programmed with a matching keyset.
         */
        mobile_access_uuid?: string | undefined
        /**
         * Unique ID assigned by the ASSA ABLOY licensing team that identifies each hotel in your credential manager.
         */
        system_id?: string | undefined
      }
    | undefined
  /**
   * Warnings associated with the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  warnings: Array<
    /**
     * Indicates that the Salto KS site has exceeded 80% of the maximum number of allowed users. Increase your subscription limit or delete some users from your site to rectify the issue.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'salto_ks_subscription_limit_almost_reached'
      } /**
     * Indicates the [access control system](https://docs.seam.co/low-level-apis/access-systems) time zone could not be determined because the reported physical location does not match the time zone configured on the physical [ACS entrances](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * @deprecated this field is deprecated.
         */
        misconfigured_acs_entrance_ids?: Array<string> | undefined
        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'time_zone_does_not_match_location'
      } /**
     * Indicates that the access control system requires additional setup before it can be fully operational. Follow the instructions in the warning message to complete the setup.
     * @deprecated
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'setup_required'
      }
  >

  /**
   * ID of the workspace that contains the [access control system](https://docs.seam.co/low-level-apis/access-systems).
   */
  workspace_id: string
}
