/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

/**
 * Represents a [user](https://docs.seam.co/low-level-apis/access-systems/user-management) in an [access system](https://docs.seam.co/low-level-apis/access-systems).
 *
 * An access system user typically refers to an individual who requires access, like an employee or resident. Each user can possess multiple credentials that serve as their keys or identifiers for access. The type of credential can vary widely. For example, in the Salto system, a user can have a PIN code, a mobile app account, and a fob. In other platforms, it is not uncommon for a user to have more than one of the same credential type, such as multiple key cards. Additionally, these credentials can have a schedule or validity period.
 *
 * For details about how to configure users in your access system, see the corresponding [system integration guide](https://docs.seam.co/device-and-system-integration-guides#access-control-systems).
 */
export type AcsUser = {
  /**
   * `starts_at` and `ends_at` timestamps for the [access system user's](https://docs.seam.co/low-level-apis/access-systems/user-management) access.
   */
  access_schedule?:
    | {
        /**
         * Date and time at which the user's access ends, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
         */
        ends_at: string | null
        /**
         * Date and time at which the user's access starts, in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
         */
        starts_at: string
      }
    | undefined
  /**
   * ID of the [access system](https://docs.seam.co/low-level-apis/access-systems) that contains the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  acs_system_id: string

  /**
   * ID of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  acs_user_id: string

  /**
   * The ID of the connected account that is associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  connected_account_id: string

  /**
   * Date and time at which the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was created.
   */
  created_at: string

  /**
   * Display name for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  display_name: string

  /**
   * @deprecated use email_address.
   */
  email?: string | undefined
  /**
   * Email address of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  email_address?: string | undefined
  /**
   * Errors associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  errors: Array<
    /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was deleted from the [access system](https://docs.seam.co/low-level-apis/access-systems) outside of Seam.
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        error_code: 'deleted_externally'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) could not be subscribed on Salto KS because the subscription limit has been exceeded.
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        error_code: 'salto_ks_subscription_limit_exceeded'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was not created on the [access system](https://docs.seam.co/low-level-apis/access-systems). This is likely due to an internal unexpected error. Contact Seam [support](mailto:support@seam.co).
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        error_code: 'failed_to_create_on_acs_system'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was not updated on the [access system](https://docs.seam.co/low-level-apis/access-systems). This is likely due to an internal unexpected error. Contact Seam [support](mailto:support@seam.co).
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        error_code: 'failed_to_update_on_acs_system'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was not deleted on the [access system](https://docs.seam.co/low-level-apis/access-systems). This is likely due to an internal unexpected error. Contact Seam [support](mailto:support@seam.co).
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        error_code: 'failed_to_delete_on_acs_system'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was created from the Seam API but also exists on Mission Control. This is unsupported. Contact Seam [support](mailto:support@seam.co).
     */
    | {
        /**
         * Date and time at which Seam created the error.
         */
        created_at: string

        error_code: 'latch_conflict_with_resident_user'

        /**
         * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
         */
        message: string
      }
  >

  /**
   * Brand-specific terminology for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) type.
   */
  external_type?:
    | 'pti_user'
    | 'brivo_user'
    | 'hid_credential_manager_user'
    | 'salto_site_user'
    | 'latch_user'
    | 'dormakaba_community_user'
    | 'salto_space_user'
    | 'avigilon_alta_user'
    | 'kisi_user'
    | undefined
  /**
   * Display name that corresponds to the brand-specific terminology for the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) type.
   */
  external_type_display_name?: string | undefined
  /**
   * Full name of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  full_name?: string | undefined
  /**
   * ID of the HID access control system associated with the user.
   */
  hid_acs_system_id?: string | undefined
  /**
   * Indicates whether Seam manages the access system user.
   */
  is_managed: boolean

  /**
   * Indicates whether the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) is currently [suspended](https://docs.seam.co/low-level-apis/access-systems/user-management/suspending-and-unsuspending-users).
   */
  is_suspended?: boolean | undefined
  /**
   * Pending mutations associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management). Seam is in the process of pushing these mutations to the integrated access system.
   */
  pending_mutations?:
    | Array<
        /**
         * Seam is in the process of pushing a user creation to the integrated access system.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of pushing a user creation to the integrated access system.
             */
            mutation_code: 'creating'
          } /**
         * Seam is in the process of pushing a user deletion to the integrated access system.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of pushing a user deletion to the integrated access system.
             */
            mutation_code: 'deleting'
          } /**
         * User exists in Seam but has not been pushed to the provider yet. Will be created when a credential is issued.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is intentionally deferring the creation of the user on the access control system until the appropriate time.
             */
            mutation_code: 'deferring_creation'

            /**
             * Optional: When the user creation is scheduled to occur.
             */
            scheduled_at?: string | null | undefined
          }
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Old access system user information.
             */
            from: {
              /**
               * Email address of the access system user.
               */
              email_address?: string | null | undefined
              /**
               * Full name of the access system user.
               */
              full_name?: string | null | undefined
              /**
               * Phone number of the access system user.
               */
              phone_number?: string | null | undefined
            }

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of pushing updated user information to the integrated access system.
             */
            mutation_code: 'updating_user_information'

            /**
             * New access system user information.
             */
            to: {
              /**
               * Email address of the access system user.
               */
              email_address?: string | null | undefined
              /**
               * Full name of the access system user.
               */
              full_name?: string | null | undefined
              /**
               * Phone number of the access system user.
               */
              phone_number?: string | null | undefined
            }
          } /**
         * Seam is in the process of pushing an access schedule update to the integrated access system.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Old access schedule information.
             */
            from: {
              /**
               * Starting time for the access schedule.
               */
              ends_at: string | null
              /**
               * Starting time for the access schedule.
               */
              starts_at: string | null
            }

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of pushing updated access schedule information to the integrated access system.
             */
            mutation_code: 'updating_access_schedule'

            /**
             * New access schedule information.
             */
            to: {
              /**
               * Starting time for the access schedule.
               */
              ends_at: string | null
              /**
               * Starting time for the access schedule.
               */
              starts_at: string | null
            }
          } /**
         * Seam is in the process of pushing a suspension state update to the integrated access system.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Old user suspension state information.
             */
            from: {
              is_suspended: boolean
            }

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of pushing updated user suspension state information to the integrated access system.
             */
            mutation_code: 'updating_suspension_state'

            /**
             * New user suspension state information.
             */
            to: {
              is_suspended: boolean
            }
          } /**
         * Seam is in the process of pushing an access group membership update to the integrated access system.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Old access group membership.
             */
            from: {
              /**
               * Old access group ID.
               */
              acs_access_group_id: string | null
            }

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of pushing updated access group membership information to the integrated access system.
             */
            mutation_code: 'updating_group_membership'

            /**
             * New access group membership.
             */
            to: {
              /**
               * New access group ID.
               */
              acs_access_group_id: string | null
            }
          } /**
         * A scheduled access group membership change is pending for this user.
         */
        | {
            /**
             * ID of the access group involved in the scheduled change.
             */
            acs_access_group_id: string

            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that a scheduled access group membership change is pending for this user.
             */
            mutation_code: 'deferring_group_membership_update'

            /**
             * Whether the user is scheduled to be added to or removed from the access group.
             */
            variant: 'adding' | 'removing'
          } /**
         * Seam is in the process of assigning or unassigning a credential to the user on the integrated access system.
         */
        | {
            /**
             * Date and time at which the mutation was created.
             */
            created_at: string

            /**
             * Previous credential assignment.
             */
            from: {
              /**
               * Previous credential ID.
               */
              acs_credential_id: string | null
            }

            /**
             * Detailed description of the mutation.
             */
            message: string

            /**
             * Mutation code to indicate that Seam is in the process of assigning or unassigning a credential to the user on the integrated access system.
             */
            mutation_code: 'updating_credential_assignment'

            /**
             * New credential assignment.
             */
            to: {
              /**
               * New credential ID.
               */
              acs_credential_id: string | null
            }
          }
      >
    | undefined
  /**
   * Phone number of the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) in E.164 format (for example, `+15555550100`).
   */
  phone_number?: string | undefined
  /**
   * Salto KS-specific metadata associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  salto_ks_metadata?:
    | {
        /**
         * Indicates whether the user holds an active subscription slot on the Salto KS site. Only subscribed users can unlock doors and count against the site's user-subscription limit. A user may not be subscribed because their access schedule has not started or has ended, the site has reached its subscription limit, or they were manually unsubscribed. This is distinct from `is_suspended`, which reflects whether the user has been explicitly blocked.
         */
        is_subscribed?: boolean | undefined
      }
    | undefined
  /**
   * Salto Space-specific metadata associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  salto_space_metadata?:
    | {
        /**
         * Indicates whether AuditOpenings is enabled for the user in the Salto Space access system.
         */
        audit_openings?: boolean | undefined
        /**
         * User ID in the Salto Space access system.
         */
        user_id?: string | undefined
      }
    | undefined
  /**
   * Email address of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  user_identity_email_address?: string | null | undefined
  /**
   * Full name of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  user_identity_full_name?: string | null | undefined
  /**
   * ID of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  user_identity_id?: string | undefined
  /**
   * Phone number of the user identity associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) in E.164 format (for example, `+15555550100`).
   */
  user_identity_phone_number?: string | null | undefined
  /**
   * Warnings associated with the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  warnings: Array<
    /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) is being deleted from the [access system](https://docs.seam.co/low-level-apis/access-systems). This is a temporary state, and the access system user will be deleted shortly.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        warning_code: 'being_deleted'
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) is not subscribed on Salto KS, so they cannot unlock doors or perform any actions. This occurs when the their access schedule hasn’t started yet, if their access schedule has ended, if the site has reached its limit for active users (subscription slots), or if they have been manually unsubscribed.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        warning_code: 'salto_ks_user_not_subscribed'
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) exists but is not currently able to gain access—for example, because their access schedule has not started yet or has ended, the access system has reached its limit for active users, or they have been unsubscribed or deactivated. Refer to the warning message for the provider-specific reason. This is distinct from `is_suspended`, which indicates the user has been explicitly blocked.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        warning_code: 'acs_user_inactive'
      } /**
     * An unknown issue occurred while syncing the state of this [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) with the provider. This issue may affect the proper functioning of this user.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        warning_code: 'unknown_issue_with_acs_user'
      } /**
     * Indicates that the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management) was created on Latch Mission Control. Please use the Latch Mission Control to manage this user.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        warning_code: 'latch_resident_user'
      }
  >

  /**
   * ID of the workspace that contains the [access system user](https://docs.seam.co/low-level-apis/access-systems/user-management).
   */
  workspace_id: string
}
