/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

export type ConnectedAccountResource = {
  accepted_capabilities: Array<
    'lock' | 'thermostat' | 'noise_sensor' | 'access_control' | 'camera'
  >

  account_type?: string | undefined
  account_type_display_name: string

  automatically_manage_new_devices: boolean

  connected_account_id: string

  created_at?: string | undefined
  custom_metadata: Record<string, unknown>

  customer_key?: string | undefined
  default_checkin_time?: string | undefined
  default_checkout_time?: string | undefined
  display_name: string

  errors: Array<
    | {
        created_at: string

        error_code: 'account_disconnected'

        is_bridge_error?: boolean | undefined
        is_connected_account_error?: boolean | undefined
        message: string
      }
    | {
        created_at: string

        error_code: 'bridge_disconnected'

        is_bridge_error?: boolean | undefined
        is_connected_account_error?: boolean | undefined
        message: string
      }
    | {
        created_at: string

        error_code: 'salto_ks_subscription_limit_exceeded'

        is_bridge_error?: boolean | undefined
        is_connected_account_error?: boolean | undefined
        message: string

        salto_ks_metadata: {
          sites?:
            | Array<{
                site_id?: string | undefined
                site_name?: string | undefined
                site_user_subscription_limit?: number | undefined
                subscribed_site_user_count?: number | undefined
              }>
            | undefined
        }
      }
    | {
        created_at: string

        error_code: 'dormakaba_sites_disconnected'

        is_bridge_error?: boolean | undefined
        is_connected_account_error?: boolean | undefined
        message: string
      }
  >

  ical_feed_origin?: string | undefined
  ical_url?: string | undefined
  image_url?: string | undefined
  time_zone?: string | undefined
  user_identifier?:
    | {
        api_url?: string | undefined
        email?: string | undefined
        exclusive?: boolean | undefined
        phone?: string | undefined
        username?: string | undefined
      }
    | undefined
  warnings: Array<
    | {
        created_at: string

        message: string

        warning_code: 'scheduled_maintenance_window'
      }
    | {
        created_at: string

        message: string

        warning_code: 'unknown_issue_with_connected_account'
      }
    | {
        created_at: string

        message: string

        salto_ks_metadata: {
          sites?:
            | Array<{
                site_id?: string | undefined
                site_name?: string | undefined
                site_user_subscription_limit?: number | undefined
                subscribed_site_user_count?: number | undefined
              }>
            | undefined
        }

        warning_code: 'salto_ks_subscription_limit_almost_reached'
      }
    | {
        created_at: string

        message: string

        warning_code: 'account_reauthorization_requested'
      }
    | {
        created_at: string

        message: string

        warning_code: 'being_deleted'
      }
    | {
        created_at: string

        message: string

        warning_code: 'provider_service_unavailable'
      }
    | {
        created_at: string

        message: string

        warning_code: 'setup_required'
      }
    | {
        created_at: string

        message: string

        warning_code: 'dormakaba_sites_unapproved'
      }
  >
}
