/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

export type MagicLinkResource = {
  created_at: string

  customer_key: string

  expires_at: string

  url: string

  workspace_id: string
}
