/* Automatically generated by codegen/smith.ts. */

export type StaffMemberResource = {
  building_keys?: Array<string> | undefined
  common_area_keys?: Array<string> | undefined
  email_address?: string | undefined
  facility_keys?: Array<string> | undefined
  listing_keys?: Array<string> | undefined
  name: string
  phone_number?: string | undefined
  property_keys?: Array<string> | undefined
  property_listing_keys?: Array<string> | undefined
  room_keys?: Array<string> | undefined
  site_keys?: Array<string> | undefined
  space_keys?: Array<string> | undefined
  staff_member_key: string
  unit_keys?: Array<string> | undefined
}
