/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

export type ThermostatDailyProgram = {
  created_at: string

  device_id: string

  name: string | null
  periods: Array<{
    climate_preset_key: string

    starts_at_time: string
  }>

  thermostat_daily_program_id: string

  workspace_id: string
}
