/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

export type UnmanagedAcsUserResource = {
  access_schedule?:
    | {
        ends_at: string | null
        starts_at: string
      }
    | undefined
  acs_system_id: string

  acs_user_id: string

  connected_account_id: string

  created_at: string

  display_name: string

  email?: string | undefined
  email_address?: string | undefined
  errors: Array<
    | {
        created_at: string

        error_code: 'deleted_externally'

        message: string
      }
    | {
        created_at: string

        error_code: 'salto_ks_subscription_limit_exceeded'

        message: string
      }
    | {
        created_at: string

        error_code: 'failed_to_create_on_acs_system'

        message: string
      }
    | {
        created_at: string

        error_code: 'failed_to_update_on_acs_system'

        message: string
      }
    | {
        created_at: string

        error_code: 'failed_to_delete_on_acs_system'

        message: string
      }
    | {
        created_at: string

        error_code: 'latch_conflict_with_resident_user'

        message: string
      }
  >

  external_type?:
    | 'pti_user'
    | 'brivo_user'
    | 'hid_credential_manager_user'
    | 'salto_site_user'
    | 'latch_user'
    | 'dormakaba_community_user'
    | 'salto_space_user'
    | 'avigilon_alta_user'
    | 'kisi_user'
    | undefined
  external_type_display_name?: string | undefined
  full_name?: string | undefined
  hid_acs_system_id?: string | undefined
  is_managed: boolean

  is_suspended?: boolean | undefined
  last_successful_sync_at: string | null
  pending_mutations?:
    | Array<
        | {
            created_at: string

            message: string

            mutation_code: 'creating'
          }
        | {
            created_at: string

            message: string

            mutation_code: 'deleting'
          }
        | {
            created_at: string

            message: string

            mutation_code: 'deferring_creation'

            scheduled_at?: string | null | undefined
          }
        | {
            created_at: string

            from: {
              email_address?: string | null | undefined
              full_name?: string | null | undefined
              phone_number?: string | null | undefined
            }

            message: string

            mutation_code: 'updating_user_information'

            to: {
              email_address?: string | null | undefined
              full_name?: string | null | undefined
              phone_number?: string | null | undefined
            }
          }
        | {
            created_at: string

            from: {
              ends_at: string | null
              starts_at: string | null
            }

            message: string

            mutation_code: 'updating_access_schedule'

            to: {
              ends_at: string | null
              starts_at: string | null
            }
          }
        | {
            created_at: string

            from: {
              is_suspended: boolean
            }

            message: string

            mutation_code: 'updating_suspension_state'

            to: {
              is_suspended: boolean
            }
          }
        | {
            created_at: string

            from: {
              acs_access_group_id: string | null
            }

            message: string

            mutation_code: 'updating_group_membership'

            to: {
              acs_access_group_id: string | null
            }
          }
        | {
            acs_access_group_id: string

            created_at: string

            message: string

            mutation_code: 'deferring_group_membership_update'

            variant: 'adding' | 'removing'
          }
        | {
            created_at: string

            from: {
              acs_credential_id: string | null
            }

            message: string

            mutation_code: 'updating_credential_assignment'

            to: {
              acs_credential_id: string | null
            }
          }
      >
    | undefined
  phone_number?: string | undefined
  salto_ks_metadata?:
    | {
        is_subscribed?: boolean | undefined
      }
    | undefined
  salto_space_metadata?:
    | {
        audit_openings?: boolean | undefined
        user_id?: string | undefined
      }
    | undefined
  user_identity_email_address?: string | null | undefined
  user_identity_full_name?: string | null | undefined
  user_identity_id?: string | undefined
  user_identity_phone_number?: string | null | undefined
  warnings: Array<
    | {
        created_at: string

        message: string

        warning_code: 'being_deleted'
      }
    | {
        created_at: string

        message: string

        warning_code: 'salto_ks_user_not_subscribed'
      }
    | {
        created_at: string

        message: string

        warning_code: 'acs_user_inactive'
      }
    | {
        created_at: string

        message: string

        warning_code: 'unknown_issue_with_acs_user'
      }
    | {
        created_at: string

        message: string

        warning_code: 'latch_resident_user'
      }
  >

  workspace_id: string
}
