/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

export type UnmanagedDeviceResource = {
  can_configure_auto_lock?: boolean | undefined
  can_hvac_cool?: boolean | undefined
  can_hvac_heat?: boolean | undefined
  can_hvac_heat_cool?: boolean | undefined
  can_program_offline_access_codes?: boolean | undefined
  can_program_online_access_codes?: boolean | undefined
  can_program_thermostat_programs_as_different_each_day?: boolean | undefined
  can_program_thermostat_programs_as_same_each_day?: boolean | undefined
  can_program_thermostat_programs_as_weekday_weekend?: boolean | undefined
  can_remotely_lock?: boolean | undefined
  can_remotely_unlock?: boolean | undefined
  can_run_thermostat_programs?: boolean | undefined
  can_simulate_connection?: boolean | undefined
  can_simulate_disconnection?: boolean | undefined
  can_simulate_hub_connection?: boolean | undefined
  can_simulate_hub_disconnection?: boolean | undefined
  can_simulate_paid_subscription?: boolean | undefined
  can_simulate_removal?: boolean | undefined
  can_turn_off_hvac?: boolean | undefined
  can_unlock_with_code?: boolean | undefined
  capabilities_supported: Array<
    | 'access_code'
    | 'lock'
    | 'noise_detection'
    | 'thermostat'
    | 'battery'
    | 'phone'
  >

  connected_account_id: string

  created_at: string

  custom_metadata: Record<string, unknown>

  device_id: string

  device_type:
    | 'akuvox_lock'
    | 'august_lock'
    | 'brivo_access_point'
    | 'butterflymx_panel'
    | 'avigilon_alta_entry'
    | 'doorking_lock'
    | 'genie_door'
    | 'igloo_lock'
    | 'linear_lock'
    | 'lockly_lock'
    | 'kwikset_lock'
    | 'nuki_lock'
    | 'salto_lock'
    | 'schlage_lock'
    | 'smartthings_lock'
    | 'wyze_lock'
    | 'yale_lock'
    | 'two_n_intercom'
    | 'controlbyweb_device'
    | 'ttlock_lock'
    | 'igloohome_lock'
    | 'four_suites_door'
    | 'dormakaba_oracode_door'
    | 'tedee_lock'
    | 'akiles_lock'
    | 'ultraloq_lock'
    | 'keyincode_lock'
    | 'omnitec_lock'
    | 'kisi_lock'
    | 'aqara_lock'
    | 'keynest_key'
    | 'noiseaware_activity_zone'
    | 'minut_sensor'
    | 'ecobee_thermostat'
    | 'nest_thermostat'
    | 'honeywell_resideo_thermostat'
    | 'tado_thermostat'
    | 'sensi_thermostat'
    | 'smartthings_thermostat'
    | 'ios_phone'
    | 'android_phone'
    | 'ring_camera'

  errors: Array<
    | {
        created_at: string

        error_code: 'account_disconnected'

        is_connected_account_error: boolean

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'salto_ks_subscription_limit_exceeded'

        is_connected_account_error: boolean

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'dormakaba_sites_disconnected'

        is_connected_account_error: boolean

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'device_offline'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'device_removed'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'hub_disconnected'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'device_disconnected'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'empty_backup_access_code_pool'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'august_lock_not_authorized'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'missing_device_credentials'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'auxiliary_heat_running'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'subscription_required'

        is_device_error: boolean

        message: string
      }
    | {
        created_at: string

        error_code: 'bridge_disconnected'

        is_bridge_error?: boolean | undefined
        is_connected_account_error?: boolean | undefined
        message: string
      }
  >

  is_managed: boolean

  location?:
    | {
        location_name?: string | undefined
        time_zone?: string | undefined
        timezone?: string | undefined
      }
    | undefined
  properties: {
    accessory_keypad?:
      | {
          battery?:
            | {
                level: number
              }
            | undefined
          is_connected: boolean
        }
      | undefined
    battery?:
      | {
          level: number

          status: 'critical' | 'low' | 'good' | 'full'
        }
      | undefined
    battery_level?: number | undefined
    image_alt_text?: string | undefined
    image_url?: string | undefined
    manufacturer?: string | undefined
    model: {
      accessory_keypad_supported?: boolean | undefined
      can_connect_accessory_keypad?: boolean | undefined
      display_name: string

      has_built_in_keypad?: boolean | undefined
      manufacturer_display_name: string

      offline_access_codes_supported?: boolean | undefined
      online_access_codes_supported?: boolean | undefined
    }

    name: string

    offline_access_codes_enabled?: boolean | undefined
    online: boolean

    online_access_codes_enabled?: boolean | undefined
  }

  warnings: Array<
    | {
        created_at: string

        message: string

        warning_code: 'partial_backup_access_code_pool'
      }
    | {
        created_at: string

        message: string

        warning_code: 'many_active_backup_codes'
      }
    | {
        created_at: string

        message: string

        warning_code: 'third_party_integration_detected'
      }
    | {
        created_at: string

        message: string

        warning_code: 'ttlock_lock_gateway_unlocking_not_enabled'
      }
    | {
        created_at: string

        message: string

        warning_code: 'ttlock_weak_gateway_signal'
      }
    | {
        created_at: string

        message: string

        warning_code: 'power_saving_mode'
      }
    | {
        created_at: string

        message: string

        warning_code: 'temperature_threshold_exceeded'
      }
    | {
        created_at: string

        message: string

        warning_code: 'device_communication_degraded'
      }
    | {
        created_at: string

        message: string

        warning_code: 'scheduled_maintenance_window'
      }
    | {
        created_at: string

        message: string

        warning_code: 'device_has_flaky_connection'
      }
    | {
        created_at: string

        message: string

        warning_code: 'salto_ks_office_mode'
      }
    | {
        created_at: string

        message: string

        warning_code: 'salto_ks_privacy_mode'
      }
    | {
        created_at: string

        message: string

        warning_code: 'privacy_mode'
      }
    | {
        created_at: string

        message: string

        warning_code: 'salto_ks_subscription_limit_almost_reached'
      }
    | {
        created_at: string

        message: string

        warning_code: 'salto_ks_lock_access_code_support_removed'
      }
    | {
        created_at: string

        message: string

        warning_code: 'unknown_issue_with_phone'
      }
    | {
        created_at: string

        message: string

        warning_code: 'lockly_time_zone_not_configured'
      }
    | {
        created_at: string

        message: string

        warning_code: 'ultraloq_time_zone_unknown'
      }
    | {
        created_at: string

        message: string

        warning_code: 'time_zone_unknown'
      }
    | {
        created_at: string

        message: string

        warning_code: 'time_zone_mismatch'
      }
    | {
        created_at: string

        message: string

        warning_code: 'two_n_device_missing_timezone'
      }
    | {
        created_at: string

        message: string

        warning_code: 'hub_required_for_additional_capabilities'
      }
    | {
        created_at: string

        message: string

        warning_code: 'provider_issue'
      }
    | {
        created_at: string

        message: string

        warning_code: 'keynest_unsupported_locker'
      }
    | {
        created_at: string

        message: string

        warning_code: 'accessory_keypad_setup_required'
      }
    | {
        created_at: string

        message: string

        warning_code: 'unreliable_online_status'
      }
    | {
        active_access_code_count: number

        created_at: string

        max_active_access_code_count: number

        message: string

        warning_code: 'max_access_codes_reached'
      }
    | {
        created_at: string

        message: string

        warning_code: 'insufficient_permissions'
      }
  >

  workspace_id: string
}
