/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

export type UserIdentity = {
  acs_user_ids: Array<string>

  created_at: string

  display_name: string

  email_address: string | null
  errors: Array<{
    acs_system_id: string

    acs_user_id: string

    created_at: string

    error_code: 'issue_with_acs_user'

    message: string
  }>

  full_name: string | null
  phone_number: string | null
  user_identity_id: string

  user_identity_key: string | null
  warnings: Array<
    | {
        created_at: string

        message: string

        warning_code: 'being_deleted'
      }
    | {
        created_at: string

        message: string

        warning_code: 'acs_user_profile_does_not_match_user_identity'
      }
  >

  workspace_id: string
}
