/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import type { Webhook } from 'lib/resources/webhook.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import {
  SeamHttpRequest,
  type SeamPaginatedRequest,
} from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

export class SeamHttpWebhooks {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpWebhooks {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpWebhooks(constructorOptions)
  }

  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpWebhooks {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpWebhooks(constructorOptions)
  }

  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpWebhooks {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpWebhooks(constructorOptions)
  }

  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpWebhooks> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpWebhooks.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpWebhooks.fromClientSessionToken(token, options)
  }

  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpWebhooks {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpWebhooks(constructorOptions)
  }

  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpWebhooks {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpWebhooks(constructorOptions)
  }

  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamPaginatedRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(request)
  }

  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Creates a new [webhook](https://docs.seam.co/developer-tools/webhooks).
   */
  create(
    parameters: WebhooksCreateParameters,
    options: WebhooksCreateOptions = {},
  ): WebhooksCreateRequest {
    return new SeamHttpRequest(this, {
      pathname: '/webhooks/create',
      method: 'POST',
      body: parameters,
      parameters,
      hasRequiredParameters: true,
      requiredParameterNames: ['url'],
      atLeastOneParameterNames: [],
      responseKey: 'webhook',
      options,
    })
  }

  /**
   * Deletes a specified [webhook](https://docs.seam.co/developer-tools/webhooks).
   */
  delete(
    parameters: WebhooksDeleteParameters,
    options: WebhooksDeleteOptions = {},
  ): WebhooksDeleteRequest {
    return new SeamHttpRequest(this, {
      pathname: '/webhooks/delete',
      method: 'DELETE',
      params: parameters,
      parameters,
      hasRequiredParameters: true,
      requiredParameterNames: ['webhook_id'],
      atLeastOneParameterNames: [],
      responseKey: undefined,
      options,
    })
  }

  /**
   * Gets a specified [webhook](https://docs.seam.co/developer-tools/webhooks).
   */
  get(
    parameters: WebhooksGetParameters,
    options: WebhooksGetOptions = {},
  ): WebhooksGetRequest {
    return new SeamHttpRequest(this, {
      pathname: '/webhooks/get',
      method: 'GET',
      params: parameters,
      parameters,
      hasRequiredParameters: true,
      requiredParameterNames: ['webhook_id'],
      atLeastOneParameterNames: [],
      responseKey: 'webhook',
      options,
    })
  }

  /**
   * Returns a list of all [webhooks](https://docs.seam.co/developer-tools/webhooks).
   */
  list(
    parameters?: WebhooksListParameters,
    options: WebhooksListOptions = {},
  ): WebhooksListRequest {
    return new SeamHttpRequest(this, {
      pathname: '/webhooks/list',
      method: 'GET',
      params: parameters,
      parameters,
      hasRequiredParameters: false,
      requiredParameterNames: [],
      atLeastOneParameterNames: [],
      responseKey: 'webhooks',
      options,
    })
  }

  /**
   * Updates a specified [webhook](https://docs.seam.co/developer-tools/webhooks).
   */
  update(
    parameters: WebhooksUpdateParameters,
    options: WebhooksUpdateOptions = {},
  ): WebhooksUpdateRequest {
    return new SeamHttpRequest(this, {
      pathname: '/webhooks/update',
      method: 'PUT',
      body: parameters,
      parameters,
      hasRequiredParameters: true,
      requiredParameterNames: ['event_types', 'webhook_id'],
      atLeastOneParameterNames: [],
      responseKey: undefined,
      options,
    })
  }
}

export type WebhooksCreateParameters = {
  /**
   * Types of events that you want the new webhook to receive.
   */
  event_types?: Array<string> | undefined
  /**
   * URL for the new webhook.
   */
  url: string
}

/**
 * @deprecated Use WebhooksCreateRequest instead.
 */
export type WebhooksCreateResponse = { webhook: Webhook }

export type WebhooksCreateRequest = SeamHttpRequest<
  WebhooksCreateResponse,
  'webhook'
>

export interface WebhooksCreateOptions {}

export type WebhooksDeleteParameters = {
  /**
   * ID of the webhook that you want to delete.
   */
  webhook_id: string
}

/**
 * @deprecated Use WebhooksDeleteRequest instead.
 */
export type WebhooksDeleteResponse = void

export type WebhooksDeleteRequest = SeamHttpRequest<void, undefined>

export interface WebhooksDeleteOptions {}

export type WebhooksGetParameters = {
  /**
   * ID of the webhook that you want to get.
   */
  webhook_id: string
}

/**
 * @deprecated Use WebhooksGetRequest instead.
 */
export type WebhooksGetResponse = { webhook: Webhook }

export type WebhooksGetRequest = SeamHttpRequest<WebhooksGetResponse, 'webhook'>

export interface WebhooksGetOptions {}

export type WebhooksListParameters = {}

/**
 * @deprecated Use WebhooksListRequest instead.
 */
export type WebhooksListResponse = { webhooks: Array<Webhook> }

export type WebhooksListRequest = SeamHttpRequest<
  WebhooksListResponse,
  'webhooks'
>

export interface WebhooksListOptions {}

export type WebhooksUpdateParameters = {
  /**
   * Types of events that you want the webhook to receive.
   */
  event_types: Array<string>

  /**
   * ID of the webhook that you want to update.
   */
  webhook_id: string
}

/**
 * @deprecated Use WebhooksUpdateRequest instead.
 */
export type WebhooksUpdateResponse = void

export type WebhooksUpdateRequest = SeamHttpRequest<void, undefined>

export interface WebhooksUpdateOptions {}
