/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file.
 */

/**
 * Represents an [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details) within an [access control system](https://docs.seam.co/low-level-apis/access-systems).
 *
 * In an access control system, an entrance is a secured door, gate, zone, or other method of entry. You can list details for all the `acs_entrance` resources in your workspace or get these details for a specific `acs_entrance`. You can also list all entrances associated with a specific credential, and you can list all credentials associated with a specific entrance.
 */
export type AcsEntrance = {
  /**
   * ID of the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  acs_entrance_id: string

  /**
   * ID of the [access control system](https://docs.seam.co/low-level-apis/access-systems) that contains the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  acs_system_id: string

  /**
   * Akiles-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  akiles_metadata?:
    | {
        /**
         * Actions the gadget exposes (for example, open).
         */
        actions?:
          | Array<{
              /**
               * ID of the gadget action.
               */
              id?: string | undefined
              /**
               * Name of the gadget action.
               */
              name?: string | undefined
            }>
          | undefined
        /**
         * ID of the Akiles gadget.
         */
        gadget_id?: string | undefined
        /**
         * ID of the Akiles site the gadget belongs to.
         */
        site_id?: string | undefined
        /**
         * Name of the Akiles site the gadget belongs to.
         */
        site_name?: string | undefined
      }
    | undefined
  /**
   * ASSA ABLOY Vostio-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  assa_abloy_vostio_metadata?:
    | {
        /**
         * Name of the door in the Vostio access system.
         */
        door_name?: string | undefined
        /**
         * Number of the door in the Vostio access system.
         */
        door_number?: number | undefined
        /**
         * Type of the door in the Vostio access system.
         */
        door_type?:
          'CommonDoor' | 'EntranceDoor' | 'GuestDoor' | 'Elevator' | undefined
        /**
         * PMS ID of the door in the Vostio access system.
         */
        pms_id?: string | undefined
        /**
         * Indicates whether keys are allowed to set the door in stand open mode in the Vostio access system.
         */
        stand_open?: boolean | undefined
      }
    | undefined
  /**
   * Avigilon Alta-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  avigilon_alta_metadata?:
    | {
        /**
         * Entry name for an Avigilon Alta system.
         */
        entry_name?: string | undefined
        /**
         * Total count of entry relays for an Avigilon Alta system.
         */
        entry_relays_total_count?: number | undefined
        /**
         * Organization name for an Avigilon Alta system.
         */
        org_name?: string | undefined
        /**
         * Site ID for an Avigilon Alta system.
         */
        site_id?: number | undefined
        /**
         * Site name for an Avigilon Alta system.
         */
        site_name?: string | undefined
        /**
         * Zone ID for an Avigilon Alta system.
         */
        zone_id?: number | undefined
        /**
         * Zone name for an Avigilon Alta system.
         */
        zone_name?: string | undefined
      }
    | undefined
  /**
   * Brivo-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  brivo_metadata?:
    | {
        /**
         * ID of the access point in the Brivo access system.
         */
        access_point_id?: string | undefined
        /**
         * ID of the site that the access point belongs to.
         */
        site_id?: number | undefined
        /**
         * Name of the site that the access point belongs to.
         */
        site_name?: string | undefined
      }
    | undefined
  /**
   * Indicates whether the ACS entrance can belong to a reservation via an access_grant.reservation_key.
   */
  can_belong_to_reservation?: boolean | undefined
  /**
   * Indicates whether the ACS entrance can be unlocked with card credentials.
   */
  can_unlock_with_card?: boolean | undefined
  /**
   * Indicates whether the ACS entrance can be unlocked with cloud key credentials.
   */
  can_unlock_with_cloud_key?: boolean | undefined
  /**
   * Indicates whether the ACS entrance can be unlocked with pin codes.
   */
  can_unlock_with_code?: boolean | undefined
  /**
   * Indicates whether the ACS entrance can be unlocked with mobile key credentials.
   */
  can_unlock_with_mobile_key?: boolean | undefined
  /**
   * ID of the [connected account](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details) associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  connected_account_id: string

  /**
   * Date and time at which the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details) was created.
   */
  created_at: string

  /**
   * Display name for the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  display_name: string

  /**
   * dormakaba Ambiance-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  dormakaba_ambiance_metadata?:
    | {
        /**
         * Name of the access point in the dormakaba Ambiance access system.
         */
        access_point_name?: string | undefined
      }
    | undefined
  /**
   * dormakaba Community-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  dormakaba_community_metadata?:
    | {
        /**
         * Type of access point profile in the dormakaba Community access system.
         */
        access_point_profile?: string | undefined
      }
    | undefined
  /**
   * Errors associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  errors: Array<{
    /**
     * Date and time at which Seam created the error.
     */
    created_at: string

    /**
     * Unique identifier of the type of error. Enables quick recognition and categorization of the issue.
     */
    error_code: string

    /**
     * Detailed description of the error. Provides insights into the issue and potentially how to rectify it.
     */
    message: string
  }>

  /**
   * Hotek-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  hotek_metadata?:
    | {
        /**
         * Display name of the entrance.
         */
        common_area_name?: string | undefined
        /**
         * Display name of the entrance.
         */
        common_area_number?: string | undefined
        /**
         * Room number of the entrance.
         */
        room_number?: string | undefined
      }
    | undefined
  /**
   * Indicates whether the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details) is currently locked.
   */
  is_locked?: boolean | undefined
  /**
   * Latch-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  latch_metadata?:
    | {
        /**
         * Accessibility type in the Latch access system.
         */
        accessibility_type?: string | undefined
        /**
         * Name of the door in the Latch access system.
         */
        door_name?: string | undefined
        /**
         * Type of the door in the Latch access system.
         */
        door_type?: string | undefined
        /**
         * Indicates whether the entrance is connected.
         */
        is_connected?: boolean | undefined
      }
    | undefined
  /**
   * Salto KS-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  salto_ks_metadata?:
    | {
        /**
         * Battery level of the door access device.
         */
        battery_level?: string | undefined
        /**
         * Name of the door in the Salto KS access system.
         */
        door_name?: string | undefined
        /**
         * Indicates whether an intrusion alarm is active on the door.
         */
        intrusion_alarm?: boolean | undefined
        /**
         * Indicates whether the door is left open.
         */
        left_open_alarm?: boolean | undefined
        /**
         * Type of the lock in the Salto KS access system.
         */
        lock_type?: string | undefined
        /**
         * Locked state of the door in the Salto KS access system.
         */
        locked_state?: string | undefined
        /**
         * Indicates whether the door access device is online.
         */
        online?: boolean | undefined
        /**
         * Indicates whether privacy mode is enabled for the lock.
         */
        privacy_mode?: boolean | undefined
      }
    | undefined
  /**
   * Salto Space-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  salto_space_metadata?:
    | {
        /**
         * Indicates whether AuditOnKeys is enabled for the door in the Salto Space access system.
         */
        audit_on_keys?: boolean | undefined
        /**
         * Description of the door in the Salto Space access system.
         */
        door_description?: string | undefined
        /**
         * Door ID in the Salto Space access system.
         */
        door_id?: string | undefined
        /**
         * Name of the door in the Salto Space access system.
         */
        door_name?: string | undefined
        /**
         * Description of the room in the Salto Space access system.
         */
        room_description?: string | undefined
        /**
         * Name of the room in the Salto Space access system.
         */
        room_name?: string | undefined
      }
    | undefined
  /**
   * IDs of the spaces that the entrance is in.
   */
  space_ids: Array<string>

  /**
   * Visionline-specific metadata associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  visionline_metadata?:
    | {
        /**
         * Category of the door in the Visionline access system.
         */
        door_category?:
          | 'entrance'
          | 'guest'
          | 'elevator reader'
          | 'common'
          | 'common (PMS)'
          | undefined
        /**
         * Name of the door in the Visionline access system.
         */
        door_name?: string | undefined
        /**
         * Profile for the door in the Visionline access system.
         */
        profiles?:
          | Array<{
              /**
               * Door profile ID in the Visionline access system.
               */
              visionline_door_profile_id?: string | undefined
              /**
               * Door profile type in the Visionline access system.
               */
              visionline_door_profile_type?:
                'BLE' | 'commonDoor' | 'touch' | undefined
            }>
          | undefined
      }
    | undefined
  /**
   * Warnings associated with the [entrance](https://docs.seam.co/low-level-apis/access-systems/retrieving-entrance-details).
   */
  warnings: Array<
    /**
     * Indicates that a change in the reported device model has been detected for this Salto KS entrance, which may occur after an IQ hub reset. Access code support may be affected. See https://help.getseam.com/articles/5098842588-salto-ks-lock-loses-access-code-support for troubleshooting steps.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'salto_ks_entrance_access_code_support_removed'
      } /**
     * Indicates that this entrance shares a zone with other entrances in Avigilon Alta and cannot be added to an access group individually.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'entrance_shares_zone'
      } /**
     * Indicates that this entrance requires additional configuration in the access control system before Seam can fully manage it.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'entrance_setup_required'
      } /**
     * Indicates that this entrance is in privacy mode. When privacy mode is enabled, access codes, mobile keys, and remote unlocks will not work unless the user has admin access.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'salto_ks_privacy_mode'
      } /**
     * Indicates that this entrance is in privacy mode. When privacy mode is enabled, access codes, mobile keys, and remote unlocks will not work unless the user has admin access.
     */
    | {
        /**
         * Date and time at which Seam created the warning.
         */
        created_at: string

        /**
         * Detailed description of the warning. Provides insights into the issue and potentially how to rectify it.
         */
        message: string

        /**
         * Unique identifier of the type of warning. Enables quick recognition and categorization of the issue.
         */
        warning_code: 'privacy_mode'
      }
  >
}
