/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import {
  assertValidRequestParameters,
  type RequireAtLeastOne,
} from 'lib/request-parameters.js'
import type { UnmanagedAccessCode } from 'lib/resources/unmanaged-access-code.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

/**
 * Client for the Seam API /access_codes/unmanaged routes.
 */
export class SeamHttpAccessCodesUnmanaged {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  /**
   * Creates a new SeamHttpAccessCodesUnmanaged from an existing HTTP client.
   */
  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpAccessCodesUnmanaged {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpAccessCodesUnmanaged(constructorOptions)
  }

  /**
   * Creates a new SeamHttpAccessCodesUnmanaged authenticated with an API key.
   */
  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpAccessCodesUnmanaged {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpAccessCodesUnmanaged(constructorOptions)
  }

  /**
   * Creates a new SeamHttpAccessCodesUnmanaged authenticated with a client session token.
   */
  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpAccessCodesUnmanaged {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpAccessCodesUnmanaged(constructorOptions)
  }

  /**
   * Creates a new SeamHttpAccessCodesUnmanaged authenticated with a client session token
   * for the user identified by the user identifier key.
   * The client session is created with the publishable key if it does not exist.
   */
  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpAccessCodesUnmanaged> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpAccessCodesUnmanaged.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpAccessCodesUnmanaged.fromClientSessionToken(token, options)
  }

  /**
   * Creates a new SeamHttpAccessCodesUnmanaged authenticated with a console session token
   * and scoped to a workspace.
   */
  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpAccessCodesUnmanaged {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpAccessCodesUnmanaged(constructorOptions)
  }

  /**
   * Creates a new SeamHttpAccessCodesUnmanaged authenticated with a personal access token
   * and scoped to a workspace.
   */
  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpAccessCodesUnmanaged {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpAccessCodesUnmanaged(constructorOptions)
  }

  /**
   * Creates a new SeamPaginator to iterate over the paginated results
   * of the request.
   */
  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  /**
   * Updates the client session token used by this client for authentication.
   *
   * @throws If this client was not created with a client session token.
   */
  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Converts an [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes) to an [access code managed through Seam](https://docs.seam.co/low-level-apis/smart-locks/access-codes).
   *
   * An unmanaged access code has a limited set of operations that you can perform on it. Once you convert an unmanaged access code to a managed access code, the full set of access code operations and lifecycle events becomes available for it.
   *
   * Note that not all device providers support converting an unmanaged access code to a managed access code.
   */
  convertToManaged(
    parameters: AccessCodesUnmanagedConvertToManagedParameters,
    options: AccessCodesUnmanagedConvertToManagedOptions = {},
  ): AccessCodesUnmanagedConvertToManagedRequest {
    assertValidRequestParameters(
      parameters,
      '/access_codes/unmanaged/convert_to_managed',
      true,
      ['access_code_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/access_codes/unmanaged/convert_to_managed',
      method: 'PATCH',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Deletes an [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
   */
  delete(
    parameters: AccessCodesUnmanagedDeleteParameters,
    options: AccessCodesUnmanagedDeleteOptions = {},
  ): AccessCodesUnmanagedDeleteRequest {
    assertValidRequestParameters(
      parameters,
      '/access_codes/unmanaged/delete',
      true,
      ['access_code_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/access_codes/unmanaged/delete',
      method: 'DELETE',
      params: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Returns a specified [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
   *
   * You must specify either `access_code_id` or both `device_id` and `code`.
   */
  get(
    parameters: AccessCodesUnmanagedGetParameters,
    options: AccessCodesUnmanagedGetOptions = {},
  ): AccessCodesUnmanagedGetRequest {
    assertValidRequestParameters(
      parameters,
      '/access_codes/unmanaged/get',
      true,
      [],
    )

    return new SeamHttpRequest(this, {
      pathname: '/access_codes/unmanaged/get',
      method: 'GET',
      params: parameters,
      responseKey: 'access_code',
      options,
    })
  }

  /**
   * Returns a list of all [unmanaged access codes](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
   */
  list(
    parameters: AccessCodesUnmanagedListParameters,
    options: AccessCodesUnmanagedListOptions = {},
  ): AccessCodesUnmanagedListRequest {
    assertValidRequestParameters(
      parameters,
      '/access_codes/unmanaged/list',
      true,
      ['device_id'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/access_codes/unmanaged/list',
      method: 'GET',
      params: parameters,
      responseKey: 'access_codes',
      options,
    })
  }

  /**
   * Updates a specified [unmanaged access code](https://docs.seam.co/low-level-apis/smart-locks/access-codes/migrating-existing-access-codes).
   */
  update(
    parameters: AccessCodesUnmanagedUpdateParameters,
    options: AccessCodesUnmanagedUpdateOptions = {},
  ): AccessCodesUnmanagedUpdateRequest {
    assertValidRequestParameters(
      parameters,
      '/access_codes/unmanaged/update',
      true,
      ['access_code_id', 'is_managed'],
    )

    return new SeamHttpRequest(this, {
      pathname: '/access_codes/unmanaged/update',
      method: 'PATCH',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }
}

export type AccessCodesUnmanagedConvertToManagedParameters = {
  /**
   * ID of the unmanaged access code that you want to convert to a managed access code.
   */
  access_code_id: string

  /**
   * Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the access code is allowed.
   */
  allow_external_modification?: boolean | undefined
  /**
   * Indicates whether to force the access code conversion. To switch management of an access code from one Seam workspace to another, set `force` to `true`.
   */
  force?: boolean | undefined
  /**
   * Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the access code is allowed.
   */
  is_external_modification_allowed?: boolean | undefined
}

/**
 * @deprecated Use AccessCodesUnmanagedConvertToManagedRequest instead.
 */
export type AccessCodesUnmanagedConvertToManagedResponse = void

export type AccessCodesUnmanagedConvertToManagedRequest = SeamHttpRequest<
  void,
  undefined
>

export interface AccessCodesUnmanagedConvertToManagedOptions {}

export type AccessCodesUnmanagedDeleteParameters = {
  /**
   * ID of the unmanaged access code that you want to delete.
   */
  access_code_id: string
}

/**
 * @deprecated Use AccessCodesUnmanagedDeleteRequest instead.
 */
export type AccessCodesUnmanagedDeleteResponse = void

export type AccessCodesUnmanagedDeleteRequest = SeamHttpRequest<void, undefined>

export interface AccessCodesUnmanagedDeleteOptions {}

export type AccessCodesUnmanagedGetParameters = RequireAtLeastOne<{
  /**
   * ID of the unmanaged access code that you want to get. You must specify either `access_code_id` or both `device_id` and `code`.
   */
  access_code_id?: string | undefined
  /**
   * Code of the unmanaged access code that you want to get. You must specify either `access_code_id` or both `device_id` and `code`.
   */
  code?: string | undefined
  /**
   * ID of the device containing the unmanaged access code that you want to get. You must specify either `access_code_id` or both `device_id` and `code`.
   */
  device_id?: string | undefined
}>

/**
 * @deprecated Use AccessCodesUnmanagedGetRequest instead.
 */
export type AccessCodesUnmanagedGetResponse = {
  access_code: UnmanagedAccessCode
}

export type AccessCodesUnmanagedGetRequest = SeamHttpRequest<
  AccessCodesUnmanagedGetResponse,
  'access_code'
>

export interface AccessCodesUnmanagedGetOptions {}

export type AccessCodesUnmanagedListParameters = {
  /**
   * ID of the device for which you want to list unmanaged access codes.
   */
  device_id: string

  /**
   * Numerical limit on the number of unmanaged access codes to return.
   */
  limit?: number | undefined
  /**
   * Identifies the specific page of results to return, obtained from the previous page's `next_page_cursor`.
   */
  page_cursor?: string | null | undefined
  /**
   * String for which to search. Filters returned access codes to include all records that satisfy a partial match using `name`, `code` or `access_code_id`.
   */
  search?: string | undefined
  /**
   * Your user ID for the user by which to filter unmanaged access codes.
   */
  user_identifier_key?: string | undefined
}

/**
 * @deprecated Use AccessCodesUnmanagedListRequest instead.
 */
export type AccessCodesUnmanagedListResponse = {
  access_codes: Array<UnmanagedAccessCode>
}

export type AccessCodesUnmanagedListRequest = SeamHttpRequest<
  AccessCodesUnmanagedListResponse,
  'access_codes'
>

export interface AccessCodesUnmanagedListOptions {}

export type AccessCodesUnmanagedUpdateParameters = {
  /**
   * ID of the unmanaged access code that you want to update.
   */
  access_code_id: string

  /**
   * Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the code is allowed.
   */
  allow_external_modification?: boolean | undefined
  /**
   * Indicates whether to force the unmanaged access code update.
   */
  force?: boolean | undefined
  /**
   * Indicates whether [external modification](https://docs.seam.co/low-level-apis/smart-locks/access-codes#external-modification) of the code is allowed.
   */
  is_external_modification_allowed?: boolean | undefined

  is_managed: boolean
}

/**
 * @deprecated Use AccessCodesUnmanagedUpdateRequest instead.
 */
export type AccessCodesUnmanagedUpdateResponse = void

export type AccessCodesUnmanagedUpdateRequest = SeamHttpRequest<void, undefined>

export interface AccessCodesUnmanagedUpdateOptions {}
