/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import type { ActionAttempt } from 'lib/resources/action-attempt.js'
import { SeamHttpActionAttempts } from 'lib/routes/action-attempts/index.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import {
  SeamHttpRequest,
  type SeamPaginatedRequest,
} from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

export class SeamHttpLocksSimulate {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpLocksSimulate {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpLocksSimulate(constructorOptions)
  }

  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpLocksSimulate {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpLocksSimulate(constructorOptions)
  }

  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpLocksSimulate {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpLocksSimulate(constructorOptions)
  }

  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpLocksSimulate> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpLocksSimulate.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpLocksSimulate.fromClientSessionToken(token, options)
  }

  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpLocksSimulate {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpLocksSimulate(constructorOptions)
  }

  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpLocksSimulate {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpLocksSimulate(constructorOptions)
  }

  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamPaginatedRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(request)
  }

  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Simulates the entry of a code on a keypad. You can only perform this action for [August](https://docs.seam.co/device-and-system-integration-guides/august-locks) devices within [sandbox workspaces](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  keypadCodeEntry(
    parameters: LocksSimulateKeypadCodeEntryParameters,
    options: LocksSimulateKeypadCodeEntryOptions = {},
  ): LocksSimulateKeypadCodeEntryRequest {
    return new SeamHttpRequest(this, {
      pathname: '/locks/simulate/keypad_code_entry',
      method: 'POST',
      body: parameters,
      parameters,
      hasRequiredParameters: true,
      requiredParameterNames: ['code', 'device_id'],
      atLeastOneParameterNames: [],
      responseKey: 'action_attempt',
      options,
      actionAttempts: () =>
        SeamHttpActionAttempts.fromClient(this.client, {
          ...this.defaults,
          waitForActionAttempt: false,
        }),
    })
  }

  /**
   * Simulates a manual lock action using a keypad. You can only perform this action for [August](https://docs.seam.co/device-and-system-integration-guides/august-locks) devices within [sandbox workspaces](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  manualLockViaKeypad(
    parameters: LocksSimulateManualLockViaKeypadParameters,
    options: LocksSimulateManualLockViaKeypadOptions = {},
  ): LocksSimulateManualLockViaKeypadRequest {
    return new SeamHttpRequest(this, {
      pathname: '/locks/simulate/manual_lock_via_keypad',
      method: 'POST',
      body: parameters,
      parameters,
      hasRequiredParameters: true,
      requiredParameterNames: ['device_id'],
      atLeastOneParameterNames: [],
      responseKey: 'action_attempt',
      options,
      actionAttempts: () =>
        SeamHttpActionAttempts.fromClient(this.client, {
          ...this.defaults,
          waitForActionAttempt: false,
        }),
    })
  }
}

export type LocksSimulateKeypadCodeEntryParameters = {
  /**
   * Code that you want to simulate entering on a keypad.
   */
  code: string

  /**
   * ID of the device for which you want to simulate a keypad code entry.
   */
  device_id: string
}

/**
 * @deprecated Use LocksSimulateKeypadCodeEntryRequest instead.
 */
export type LocksSimulateKeypadCodeEntryResponse = {
  action_attempt: ActionAttempt
}

export type LocksSimulateKeypadCodeEntryRequest = SeamHttpRequest<
  LocksSimulateKeypadCodeEntryResponse,
  'action_attempt'
>

export type LocksSimulateKeypadCodeEntryOptions = Pick<
  SeamHttpRequestOptions,
  'waitForActionAttempt'
>

export type LocksSimulateManualLockViaKeypadParameters = {
  /**
   * ID of the device for which you want to simulate a manual lock action using a keypad.
   */
  device_id: string
}

/**
 * @deprecated Use LocksSimulateManualLockViaKeypadRequest instead.
 */
export type LocksSimulateManualLockViaKeypadResponse = {
  action_attempt: ActionAttempt
}

export type LocksSimulateManualLockViaKeypadRequest = SeamHttpRequest<
  LocksSimulateManualLockViaKeypadResponse,
  'action_attempt'
>

export type LocksSimulateManualLockViaKeypadOptions = Pick<
  SeamHttpRequestOptions,
  'waitForActionAttempt'
>
