/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import type {
  RouteRequestBody,
  RouteRequestParams,
  RouteResponse,
} from '@seamapi/types/connect'

import { seamApiLtsVersion } from 'lib/lts-version.js'
import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/seam/connect/auth.js'
import { type Client, createClient } from 'lib/seam/connect/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/seam/connect/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/seam/connect/parse-options.js'
import { SeamHttpClientSessions } from 'lib/seam/connect/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam/connect/seam-http-request.js'
import { SeamPaginator } from 'lib/seam/connect/seam-paginator.js'
import type { SetNonNullable } from 'lib/types.js'

export class SeamHttpSeamBridgeV1BridgeClientSessions {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>
  readonly ltsVersion = seamApiLtsVersion
  static ltsVersion = seamApiLtsVersion

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    if (!options.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpSeamBridgeV1BridgeClientSessions {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpSeamBridgeV1BridgeClientSessions(constructorOptions)
  }

  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpSeamBridgeV1BridgeClientSessions {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpSeamBridgeV1BridgeClientSessions(constructorOptions)
  }

  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpSeamBridgeV1BridgeClientSessions {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpSeamBridgeV1BridgeClientSessions(constructorOptions)
  }

  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpSeamBridgeV1BridgeClientSessions> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpSeamBridgeV1BridgeClientSessions.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpSeamBridgeV1BridgeClientSessions.fromClientSessionToken(
      token,
      options,
    )
  }

  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpSeamBridgeV1BridgeClientSessions {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpSeamBridgeV1BridgeClientSessions(constructorOptions)
  }

  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpSeamBridgeV1BridgeClientSessions {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpSeamBridgeV1BridgeClientSessions(constructorOptions)
  }

  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  create(
    body?: SeamBridgeV1BridgeClientSessionsCreateBody,
  ): SeamHttpRequest<
    SeamBridgeV1BridgeClientSessionsCreateResponse,
    'bridge_client_session'
  > {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname: '/seam/bridge/v1/bridge_client_sessions/create',
      method: 'POST',
      body,
      responseKey: 'bridge_client_session',
    })
  }

  get(
    params?: SeamBridgeV1BridgeClientSessionsGetParams,
  ): SeamHttpRequest<
    SeamBridgeV1BridgeClientSessionsGetResponse,
    'bridge_client_session'
  > {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname: '/seam/bridge/v1/bridge_client_sessions/get',
      method: 'GET',
      params,
      responseKey: 'bridge_client_session',
    })
  }

  refreshTelemetryToken(
    body?: SeamBridgeV1BridgeClientSessionsRefreshTelemetryTokenBody,
  ): SeamHttpRequest<
    SeamBridgeV1BridgeClientSessionsRefreshTelemetryTokenResponse,
    'bridge_client_session'
  > {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname:
        '/seam/bridge/v1/bridge_client_sessions/refresh_telemetry_token',
      method: 'POST',
      body,
      responseKey: 'bridge_client_session',
    })
  }

  regeneratePairingCode(
    body?: SeamBridgeV1BridgeClientSessionsRegeneratePairingCodeBody,
  ): SeamHttpRequest<
    SeamBridgeV1BridgeClientSessionsRegeneratePairingCodeResponse,
    'bridge_client_session'
  > {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname:
        '/seam/bridge/v1/bridge_client_sessions/regenerate_pairing_code',
      method: 'POST',
      body,
      responseKey: 'bridge_client_session',
    })
  }

  reportStatus(
    body?: SeamBridgeV1BridgeClientSessionsReportStatusBody,
  ): SeamHttpRequest<void, undefined> {
    if (!this.defaults.isUndocumentedApiEnabled) {
      throw new Error(
        'Cannot use undocumented API without isUndocumentedApiEnabled',
      )
    }
    return new SeamHttpRequest(this, {
      pathname: '/seam/bridge/v1/bridge_client_sessions/report_status',
      method: 'POST',
      body,
      responseKey: undefined,
    })
  }
}

export type SeamBridgeV1BridgeClientSessionsCreateBody =
  RouteRequestBody<'/seam/bridge/v1/bridge_client_sessions/create'>

export type SeamBridgeV1BridgeClientSessionsCreateResponse = SetNonNullable<
  Required<RouteResponse<'/seam/bridge/v1/bridge_client_sessions/create'>>
>

export type SeamBridgeV1BridgeClientSessionsCreateOptions = never

export type SeamBridgeV1BridgeClientSessionsGetParams =
  RouteRequestParams<'/seam/bridge/v1/bridge_client_sessions/get'>

export type SeamBridgeV1BridgeClientSessionsGetResponse = SetNonNullable<
  Required<RouteResponse<'/seam/bridge/v1/bridge_client_sessions/get'>>
>

export type SeamBridgeV1BridgeClientSessionsGetOptions = never

export type SeamBridgeV1BridgeClientSessionsRefreshTelemetryTokenBody =
  RouteRequestBody<'/seam/bridge/v1/bridge_client_sessions/refresh_telemetry_token'>

export type SeamBridgeV1BridgeClientSessionsRefreshTelemetryTokenResponse =
  SetNonNullable<
    Required<
      RouteResponse<'/seam/bridge/v1/bridge_client_sessions/refresh_telemetry_token'>
    >
  >

export type SeamBridgeV1BridgeClientSessionsRefreshTelemetryTokenOptions = never

export type SeamBridgeV1BridgeClientSessionsRegeneratePairingCodeBody =
  RouteRequestBody<'/seam/bridge/v1/bridge_client_sessions/regenerate_pairing_code'>

export type SeamBridgeV1BridgeClientSessionsRegeneratePairingCodeResponse =
  SetNonNullable<
    Required<
      RouteResponse<'/seam/bridge/v1/bridge_client_sessions/regenerate_pairing_code'>
    >
  >

export type SeamBridgeV1BridgeClientSessionsRegeneratePairingCodeOptions = never

export type SeamBridgeV1BridgeClientSessionsReportStatusBody =
  RouteRequestBody<'/seam/bridge/v1/bridge_client_sessions/report_status'>

export type SeamBridgeV1BridgeClientSessionsReportStatusResponse =
  SetNonNullable<
    Required<
      RouteResponse<'/seam/bridge/v1/bridge_client_sessions/report_status'>
    >
  >

export type SeamBridgeV1BridgeClientSessionsReportStatusOptions = never
