/*
 * Automatically generated by codegen/smith.ts.
 * Do not edit this file or add other files to this directory.
 */

import {
  getAuthHeadersForClientSessionToken,
  warnOnInsecureuserIdentifierKey,
} from 'lib/auth.js'
import { type Client, createClient } from 'lib/client.js'
import {
  isSeamHttpOptionsWithApiKey,
  isSeamHttpOptionsWithClient,
  isSeamHttpOptionsWithClientSessionToken,
  isSeamHttpOptionsWithConsoleSessionToken,
  isSeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpFromPublishableKeyOptions,
  SeamHttpInvalidOptionsError,
  type SeamHttpOptions,
  type SeamHttpOptionsWithApiKey,
  type SeamHttpOptionsWithClient,
  type SeamHttpOptionsWithClientSessionToken,
  type SeamHttpOptionsWithConsoleSessionToken,
  type SeamHttpOptionsWithPersonalAccessToken,
  type SeamHttpRequestOptions,
} from 'lib/options.js'
import {
  limitToSeamHttpRequestOptions,
  parseOptions,
} from 'lib/parse-options.js'
import { assertValidRequestParameters } from 'lib/request-parameters.js'
import { SeamHttpClientSessions } from 'lib/routes/client-sessions/index.js'
import { SeamHttpRequest } from 'lib/seam-http-request.js'
import { SeamPaginator } from 'lib/seam-paginator.js'

export class SeamHttpAcsEncodersSimulate {
  client: Client
  readonly defaults: Required<SeamHttpRequestOptions>

  constructor(apiKeyOrOptions: string | SeamHttpOptions = {}) {
    const options = parseOptions(apiKeyOrOptions)
    this.client = 'client' in options ? options.client : createClient(options)
    this.defaults = limitToSeamHttpRequestOptions(options)
  }

  static fromClient(
    client: SeamHttpOptionsWithClient['client'],
    options: Omit<SeamHttpOptionsWithClient, 'client'> = {},
  ): SeamHttpAcsEncodersSimulate {
    const constructorOptions = { ...options, client }
    if (!isSeamHttpOptionsWithClient(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing client')
    }
    return new SeamHttpAcsEncodersSimulate(constructorOptions)
  }

  static fromApiKey(
    apiKey: SeamHttpOptionsWithApiKey['apiKey'],
    options: Omit<SeamHttpOptionsWithApiKey, 'apiKey'> = {},
  ): SeamHttpAcsEncodersSimulate {
    const constructorOptions = { ...options, apiKey }
    if (!isSeamHttpOptionsWithApiKey(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing apiKey')
    }
    return new SeamHttpAcsEncodersSimulate(constructorOptions)
  }

  static fromClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
    options: Omit<
      SeamHttpOptionsWithClientSessionToken,
      'clientSessionToken'
    > = {},
  ): SeamHttpAcsEncodersSimulate {
    const constructorOptions = { ...options, clientSessionToken }
    if (!isSeamHttpOptionsWithClientSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError('Missing clientSessionToken')
    }
    return new SeamHttpAcsEncodersSimulate(constructorOptions)
  }

  static async fromPublishableKey(
    publishableKey: string,
    userIdentifierKey: string,
    options: SeamHttpFromPublishableKeyOptions = {},
  ): Promise<SeamHttpAcsEncodersSimulate> {
    warnOnInsecureuserIdentifierKey(userIdentifierKey)
    const clientOptions = parseOptions({ ...options, publishableKey })
    if (isSeamHttpOptionsWithClient(clientOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'The client option cannot be used with SeamHttpAcsEncodersSimulate.fromPublishableKey',
      )
    }
    const client = createClient(clientOptions)
    const clientSessions = SeamHttpClientSessions.fromClient(client)
    const { token } = await clientSessions.getOrCreate({
      user_identifier_key: userIdentifierKey,
    })
    return SeamHttpAcsEncodersSimulate.fromClientSessionToken(token, options)
  }

  static fromConsoleSessionToken(
    consoleSessionToken: SeamHttpOptionsWithConsoleSessionToken['consoleSessionToken'],
    workspaceId: SeamHttpOptionsWithConsoleSessionToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithConsoleSessionToken,
      'consoleSessionToken' | 'workspaceId'
    > = {},
  ): SeamHttpAcsEncodersSimulate {
    const constructorOptions = { ...options, consoleSessionToken, workspaceId }
    if (!isSeamHttpOptionsWithConsoleSessionToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing consoleSessionToken or workspaceId',
      )
    }
    return new SeamHttpAcsEncodersSimulate(constructorOptions)
  }

  static fromPersonalAccessToken(
    personalAccessToken: SeamHttpOptionsWithPersonalAccessToken['personalAccessToken'],
    workspaceId: SeamHttpOptionsWithPersonalAccessToken['workspaceId'],
    options: Omit<
      SeamHttpOptionsWithPersonalAccessToken,
      'personalAccessToken' | 'workspaceId'
    > = {},
  ): SeamHttpAcsEncodersSimulate {
    const constructorOptions = { ...options, personalAccessToken, workspaceId }
    if (!isSeamHttpOptionsWithPersonalAccessToken(constructorOptions)) {
      throw new SeamHttpInvalidOptionsError(
        'Missing personalAccessToken or workspaceId',
      )
    }
    return new SeamHttpAcsEncodersSimulate(constructorOptions)
  }

  createPaginator<const TResponse, const TResponseKey extends keyof TResponse>(
    request: SeamHttpRequest<TResponse, TResponseKey>,
  ): SeamPaginator<TResponse, TResponseKey> {
    return new SeamPaginator<TResponse, TResponseKey>(this, request)
  }

  async updateClientSessionToken(
    clientSessionToken: SeamHttpOptionsWithClientSessionToken['clientSessionToken'],
  ): Promise<void> {
    const { headers } = this.client.defaults
    const authHeaders = getAuthHeadersForClientSessionToken({
      clientSessionToken,
    })
    for (const key of Object.keys(authHeaders)) {
      if (headers[key] == null) {
        throw new Error(
          'Cannot update a clientSessionToken on a client created without a clientSessionToken',
        )
      }
    }
    this.client.defaults.headers = { ...headers, ...authHeaders }
    const clientSessions = SeamHttpClientSessions.fromClient(this.client)
    await clientSessions.get()
  }

  /**
   * Simulates that the next attempt to encode a [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) using the specified [encoder](https://docs.seam.co/low-level-apis/access-systems/working-with-card-encoders-and-scanners) will fail. You can only perform this action within a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  nextCredentialEncodeWillFail(
    parameters: AcsEncodersSimulateNextCredentialEncodeWillFailParameters,
    options: AcsEncodersSimulateNextCredentialEncodeWillFailOptions = {},
  ): AcsEncodersSimulateNextCredentialEncodeWillFailRequest {
    assertValidRequestParameters(
      parameters,
      '/acs/encoders/simulate/next_credential_encode_will_fail',
      true,
    )

    return new SeamHttpRequest(this, {
      pathname: '/acs/encoders/simulate/next_credential_encode_will_fail',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates that the next attempt to encode a [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) using the specified [encoder](https://docs.seam.co/low-level-apis/access-systems/working-with-card-encoders-and-scanners) will succeed. You can only perform this action within a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  nextCredentialEncodeWillSucceed(
    parameters: AcsEncodersSimulateNextCredentialEncodeWillSucceedParameters,
    options: AcsEncodersSimulateNextCredentialEncodeWillSucceedOptions = {},
  ): AcsEncodersSimulateNextCredentialEncodeWillSucceedRequest {
    assertValidRequestParameters(
      parameters,
      '/acs/encoders/simulate/next_credential_encode_will_succeed',
      true,
    )

    return new SeamHttpRequest(this, {
      pathname: '/acs/encoders/simulate/next_credential_encode_will_succeed',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates that the next attempt to scan a [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) using the specified [encoder](https://docs.seam.co/low-level-apis/access-systems/working-with-card-encoders-and-scanners) will fail. You can only perform this action within a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  nextCredentialScanWillFail(
    parameters: AcsEncodersSimulateNextCredentialScanWillFailParameters,
    options: AcsEncodersSimulateNextCredentialScanWillFailOptions = {},
  ): AcsEncodersSimulateNextCredentialScanWillFailRequest {
    assertValidRequestParameters(
      parameters,
      '/acs/encoders/simulate/next_credential_scan_will_fail',
      true,
    )

    return new SeamHttpRequest(this, {
      pathname: '/acs/encoders/simulate/next_credential_scan_will_fail',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }

  /**
   * Simulates that the next attempt to scan a [credential](https://docs.seam.co/low-level-apis/access-systems/managing-credentials) using the specified [encoder](https://docs.seam.co/low-level-apis/access-systems/working-with-card-encoders-and-scanners) will succeed. You can only perform this action within a [sandbox workspace](https://docs.seam.co/core-concepts/workspaces#sandbox-workspaces).
   */
  nextCredentialScanWillSucceed(
    parameters: AcsEncodersSimulateNextCredentialScanWillSucceedParameters,
    options: AcsEncodersSimulateNextCredentialScanWillSucceedOptions = {},
  ): AcsEncodersSimulateNextCredentialScanWillSucceedRequest {
    assertValidRequestParameters(
      parameters,
      '/acs/encoders/simulate/next_credential_scan_will_succeed',
      true,
    )

    return new SeamHttpRequest(this, {
      pathname: '/acs/encoders/simulate/next_credential_scan_will_succeed',
      method: 'POST',
      body: parameters,
      responseKey: undefined,
      options,
    })
  }
}

export type AcsEncodersSimulateNextCredentialEncodeWillFailParameters = {
  /**
   * ID of the `acs_encoder` that will be used in the next request to encode the `acs_credential`.
   */
  acs_encoder_id: string

  /**
   * Code of the error to simulate.
   */
  error_code?:
    | 'no_credential_on_encoder'
    | 'encoding_interrupted'
    | 'uncategorized_error'
    | 'action_attempt_expired'
    | undefined
  /**
   * ID of the `acs_credential` that will fail to be encoded onto a card in the next request.
   */
  acs_credential_id?: string | undefined
}

/**
 * @deprecated Use AcsEncodersSimulateNextCredentialEncodeWillFailRequest instead.
 */
export type AcsEncodersSimulateNextCredentialEncodeWillFailResponse = void

export type AcsEncodersSimulateNextCredentialEncodeWillFailRequest =
  SeamHttpRequest<void, undefined>

export interface AcsEncodersSimulateNextCredentialEncodeWillFailOptions {}

export type AcsEncodersSimulateNextCredentialEncodeWillSucceedParameters = {
  /**
   * ID of the `acs_encoder` that will be used in the next request to encode the `acs_credential`.
   */
  acs_encoder_id: string

  /**
   * Scenario to simulate.
   */
  scenario?: 'credential_is_issued' | undefined
}

/**
 * @deprecated Use AcsEncodersSimulateNextCredentialEncodeWillSucceedRequest instead.
 */
export type AcsEncodersSimulateNextCredentialEncodeWillSucceedResponse = void

export type AcsEncodersSimulateNextCredentialEncodeWillSucceedRequest =
  SeamHttpRequest<void, undefined>

export interface AcsEncodersSimulateNextCredentialEncodeWillSucceedOptions {}

export type AcsEncodersSimulateNextCredentialScanWillFailParameters = {
  /**
   * ID of the `acs_encoder` that will fail to scan the `acs_credential` in the next request.
   */
  acs_encoder_id: string

  error_code?:
    | 'no_credential_on_encoder'
    | 'uncategorized_error'
    | 'action_attempt_expired'
    | undefined

  acs_credential_id_on_seam?: string | undefined
}

/**
 * @deprecated Use AcsEncodersSimulateNextCredentialScanWillFailRequest instead.
 */
export type AcsEncodersSimulateNextCredentialScanWillFailResponse = void

export type AcsEncodersSimulateNextCredentialScanWillFailRequest =
  SeamHttpRequest<void, undefined>

export interface AcsEncodersSimulateNextCredentialScanWillFailOptions {}

export type AcsEncodersSimulateNextCredentialScanWillSucceedParameters = {
  /**
   * ID of the Seam `acs_credential` that matches the `acs_credential` on the encoder in this simulation.
   */
  acs_credential_id_on_seam?: string | undefined
  /**
   * ID of the `acs_encoder` that will be used in the next request to scan the `acs_credential`.
   */
  acs_encoder_id: string

  /**
   * Scenario to simulate.
   */
  scenario?:
    | 'credential_exists_on_seam'
    | 'credential_on_encoder_needs_update'
    | 'credential_does_not_exist_on_seam'
    | 'credential_on_encoder_is_empty'
    | undefined
}

/**
 * @deprecated Use AcsEncodersSimulateNextCredentialScanWillSucceedRequest instead.
 */
export type AcsEncodersSimulateNextCredentialScanWillSucceedResponse = void

export type AcsEncodersSimulateNextCredentialScanWillSucceedRequest =
  SeamHttpRequest<void, undefined>

export interface AcsEncodersSimulateNextCredentialScanWillSucceedOptions {}
